### ISSUE TITLE
Add Position Slider

### ISSUE THREAD

**Issue by webmastak** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#11]
Please add position slider as in gnome-shell-extensions-mediaplayer.

**Comment by JasonLG1979** [comment]
As explained by me [here](https://extensions.gnome.org/extension/1379/mpris-indicator-button):

"seeking and keeping track of track position in general is not implemented at all in some players (Spotify for example) and not correctly in a great many others. It depends on a great many things that the player has to do just right. With the current state of players' MPRIS interfaces it would require a bunch of hacky workarounds, player sniffing and white/blacklists. Even then it's just not worth it. It just ends up with me trouble shooting and fixing or at least filing a bunch of bug reports on random broken players. The end result being something that may or may not work but that's out of my control."

Unfortunately the features that are or will be exposed/enabled in this extension depend on the greater state of the majority of player's MPRIS interfaces. (basically what do most players *not* fuck up).

In theory I should be able to expose all the functionality/features that are *supposed to be* a part of the various MPRIS interfaces, but in reality all that would do is lead to a flood of "[*random feature*] doesn't work with [*random player*]" bug reports being filed against this extension.

**Comment by JasonLG1979** [comment]
Also in the case of a position slider in particular adding it would add a fair amount of complexity for something that might not even work.

**Comment by webmastak** [comment]
I don't understand why you abandoned **gnome-shell-extensions-mediaplayer**, this is a better extension!

gnome-shell-extension-mpris-indicator-button - too simple, switch tracks can in the application itself or on the web page.

**Comment by JasonLG1979** [comment]
> I don't understand why you abandoned **gnome-shell-extensions-mediaplayer**, this is a better extension!

Then take over maintainership of the repo or fork it and continue it's development. The code is still out there. 

> gnome-shell-extension-mpris-indicator-button - too simple and little functional, switch tracks can in the application itself or on the web page.

Then don't use it if you don't like it. I'm sorry if you're under the misconception that since I released this extension for anyone to use if they choose that I wrote it for everyone. I wrote it primarily for myself. There is no guarantee that you or anyone else will find it useful as stated in the license.

**Comment by JasonLG1979** [comment]
Mpris Indicator Button extension for Gnome Shell 3.32+
 Copyright 2019 Jason Gray (JasonLG1979)
 
 This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 **This program is distributed in the *hope* that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.**
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 If this extension breaks your desktop you get to keep all of the pieces...

**Comment by webmastak** [comment]
Show position slider for players that support it correctly. 
For example **Rhythmbox** and other analogues.
It would be nice. 😉
