### ISSUE TITLE
Feature porting from gnome-shell-extensions-mediaplayer

### ISSUE THREAD

**Issue by JasonLG1979** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#12]
Not an exhaustive list of all of the features and settings from [**gnome-shell-extensions-mediaplayer**](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer), more of a general list of features I have seen people asking about or features that I personally like/use. If you don't see a feature specifically listed the answer is most likely going to be "*Not happening.*"

You are of course free to takeover maintainership of [**gnome-shell-extensions-mediaplayer**](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer) or fork it and/or this extension and do the work yourself if you see anything on this list that you don't like.

**Position Slider:** *Not happening.*

**Ratings in any form:** *Not happening.*

**Changing position of the indicator or putting it in the system menu:** *Not happening.*

**Album covers in the panel:** *Not happening.*

**Playback status in the panel:** *Not happening.*

**Track info text in the panel:** *Maybe.* See [here](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/6)

**Repeat and random buttons:** ~~*Maybe.*~~ **DONE**

**TrackList and PlayList interfaces:** *Maybe.*

**Comment by JasonLG1979** [comment]
Here's a little update on what I have been working on:
![new features](https://user-images.githubusercontent.com/6667703/63459000-6b018900-c419-11e9-8a06-a8f7ea1903cb.png)


The updates include:

Tracklist and playlist interface support.

A quit button.

Slightly better widget alignment.

A separator between players. (still on the fence on this).

An arrow to indicate the current player if there are more than one in the menu. And to indicate current items in the tracklist and playlist menus. I can't use the standard ornament because it uses a Unicode bullet, that the screen reader says aloud when reading the track info. So in the case above it would say. "Spotify; Bullet, Tool, Crawl Away" if I were to use the default ornament.

As always the features require no user interaction. If the player supports them they will show up if not they won't. Above is Pithos and Spotify. Pithos follows MPRIS spec and has support for the tracklist and playlist interfaces (full disclosure: I co-wrote Pithos' MPRIS implementation) and Spotify which doesn't even support all of the player interface.

**Comment by JasonLG1979** [comment]
There are some major internal changes in the pipe for GNOME 3.34 so you can expect an update shortly after Ubuntu 19.10 and Fedora 31 is released.

**Comment by JasonLG1979** [comment]
Another update:

I'm still ironing out a few wrinkles but I should be pushing something for people to start testing tomorrow. I'm still not planning on pushing an update to the extensions site until after Ubuntu 19.10.

The update will include:

3.34 support
TrackList interface support
PlayLists interface support
A quit button
Better widget alignment
A separator between players
An arrow to indicate the current player if there are more than one in the menu
Focusing a player will skip the annoying focus stealing prevention "Player is Ready" popup notification and just focus the damn player.

**Comment by JasonLG1979** [comment]
Oh, a feature I forgot to mention. The cover art size is no longer hard coded. The cover art will size it self to the text next to it. That should help it blend in with different themes and scaling factors.

**Comment by JasonLG1979** [comment]
An update has been pushed for the brave among you who are running GNOME 3.34.

**Comment by terencode** [comment]
Some questions/thoughts:

- Why is Position Slider not happening?

- I find the current player arrow not a good indicator of what player is selected because it's very similar to the one you have to signal something is a drop down menu. What about a dot instead? Or a colored vertical bar like so:

![image](https://user-images.githubusercontent.com/12665563/65692331-a4f62880-e072-11e9-970b-db7a8b654dc6.png)


- The quit button looks ok but it'd be better if it could be highlighted when moving the mouse over it.

![image](https://user-images.githubusercontent.com/12665563/65692785-7fb5ea00-e073-11e9-979e-bf21aa35c8f6.png)

**Comment by JasonLG1979** [comment]
> * Why is Position Slider not happening?

1. A great many players do not support the feature.

2. Of those that do a great many mess it up and it's next to impossible to tell programmatically if it works correctly.

3. It would add a huge amount of complexity for a feature that would work, optimistically 50% of the time.

> * I find the current player arrow not a good indicator of what player is selected because it's very similar to the one you have to signal something is a drop down menu. What about a dot instead? Or a colored vertical bar like so:

I didn't use the dot because the screen reader in GNOME Shell reads the name of the dot because the dot is a unicode char not an icon. So what should be "Spotify; Tool, Crawl Away" becomes "Spotify; Bullet, Tool, Crawl Away" when read aloud by the screen reader. I like the sidebar idea if you can get it to match the theme's colors.

> * The quit button looks ok but it'd be better if it could be highlighted when moving the mouse over it.

I tried to use built in CSS classes as much as possible. Although the X does light up when you mouse over it. I purposely made it a small target to minimize accidental clicks when user actually intends to raise the player.

**Comment by terencode** [comment]
- Ok I understand for the position slider, that's just too bad...

- I don't know how to program the sidebar thing unfortunately. Would you be able to have a look and make it match the theme accent colour?

- Ok now that you mention it, I do see the X light up, but it's very subtle. How about making it change colour to red? I understand the decision of making the click area small though.

**Comment by JasonLG1979** [comment]
> * How about making it change colour to red?

That's possible. I'll see what I can come up with and see how it looks.

**Comment by JasonLG1979** [comment]
@terencode I tried red and it looked out of place because generally speaking there are no other buttons in the Shell except system buttons at the bottom of the main menu and they aren't red and they are HUGE, I don't want to use their style class.

As far as the arrow icon is concerned I'll look to see if there's a different icon I can use.

**Comment by terencode** [comment]
> I tried red and it looked out of place

What if you try theme accent color?


>As far as the arrow icon is concerned I'll look to see if there's a different icon I can use.

Not possible to do the vertical line thing?

**Comment by JasonLG1979** [comment]
> What if you try theme accent color?

I can use the same style class as the close button in the overview. I'll see how that looks.

> Not possible to do the vertical line thing?

It should be. I'm not what you call a CSS wizard,lol!!! It's trivial to put a line next to items it's another thing to make sure it always matches the theme color and size.

**Comment by terencode** [comment]
Alright ;)

**Comment by JasonLG1979** [comment]
Here's what it looks like with the default GNOME Shell theme:
![screenshot](https://user-images.githubusercontent.com/6667703/65806351-c3c9ed00-e14e-11e9-8a25-6bbc948b02ee.png)


I'll check to see what it looks like in Ubuntu's Shell theme if it doesn't look bad I might go with it.

**Comment by JasonLG1979** [comment]
![screenshot2](https://user-images.githubusercontent.com/6667703/65806793-eeb54080-e150-11e9-8794-8b23aa8cd2c1.png)

Not bad. What do you think @terencode

**Comment by terencode** [comment]
Exactly how I envisioned it  @JasonLG1979 :ok_hand:

**Comment by JasonLG1979** [comment]
@terencode I still haven't decided. In place of the arrow to indicate the current item I think I'm just going to make my own bullet icon. Probability just a 6 - 8px solid circle. I'm very surprised there isn't already a bullet icon?

**Comment by terencode** [comment]
What about using `media-record-symbolic` ?

**Comment by JasonLG1979** [comment]
I saw that but depending on the theme who knows what it looks like. In Ubuntu's theme it's red for example.

**Comment by terencode** [comment]
Out of ideas then :/ easier to do yourself the bullet than the vertical bar?

**Comment by JasonLG1979** [comment]
> Out of ideas then :/ easier to do yourself the bullet than the vertical bar?

For sure.

**Comment by JasonLG1979** [comment]
@terencode OK so I can get Gtk/GNOME shell to load any icon I create so I'm going to go with ```media-record-symbolic``` for the bullet but it's rather huge (10 - 12px depending on the theme) so I managed to shrink it down with a little CSS fuckery.

As far as the close button after looking at various themes it can look rather weird sometimes so I've decided to go with your original idea and just make it red on hover.

It doesn't look so bad. What do you think?
![Screenshot from 2019-09-28 19-04-41](https://user-images.githubusercontent.com/6667703/65823827-1d9be700-e223-11e9-8f0b-a70e4c0a423f.png)

I used red's from the GNOME icon HIG palette so they shouldn't look horribly out of place anywhere. The icon only goes red on hover otherwise it's just the "X" close window icon. Note that that's the size of ```media-record-symbolic``` at 1/2 size. At full size it's way to big.

**Comment by JasonLG1979** [comment]
There you go @terencode. Try that out and let me know what you think.

**Comment by terencode** [comment]
Not bad indeed.
Here are some minor issues:

- The dot is too close to the left menu border, it feels better to have it at half distance

- The circle needs one more pixel to its radius, otherwise, the cross is off-centered.

Before:
![image](https://user-images.githubusercontent.com/12665563/65828891-241c7400-e2a0-11e9-898c-467a8e0774f8.png)

After:
![image](https://user-images.githubusercontent.com/12665563/65828886-15ce5800-e2a0-11e9-8cd4-c35bae245016.png)

**Comment by JasonLG1979** [comment]
> * The dot is too close to the left menu border, it feels better to have it at half distance

I agree I will see what I can do to move it over just a tiny bit for players.

> * The circle needs one more pixel to its radius, otherwise, the cross is off-centered.

I really can't do anything about that. Different themes may and do have different sized dots and placement. What I mean is that the icon itself in total will be 16px but the actual dot itself maybe a different size and be placed anywhere inside the 16px bounds of the icon. I can control the over all size and placement of the icon but not the size of the dot or it's placement inside the bounds of the icon.

**Comment by terencode** [comment]
For the second point I was talking about the close button.

**Comment by JasonLG1979** [comment]
Here I nudged the bullet over as far as it can go.

![screenshot9999](https://user-images.githubusercontent.com/6667703/65832345-caa84b00-e287-11e9-817d-12921dc3832e.png)

> For the second point I was talking about the close button.

No part of the close button is defined in pixels. It's all in em. That is done so it scales predicatively since it is next to text and the text pretty much sets the height of the box not counting padding. By default 1.09em = 16px with font scaling at 1. So the close button is 1.635em which = 24px again if font scaling is 1. The close button will always be as close to the center vertically as possible inside the box but it maybe off by a pixel on some themes if (box - button) / 2 != a whole number. You can't render a 1/2 a pixel.

On the default theme it is perfectly centered.
![Screenshot from 2019-09-29 07-01-50](https://user-images.githubusercontent.com/6667703/65832494-296ec400-e28a-11e9-9608-a916ae1be2c1.png)

**Comment by terencode** [comment]
Ah ok makes sense, thanks.
The dot looks better now.

**Comment by JasonLG1979** [comment]
Ok, give me a sec and I'll push that.

**Comment by JasonLG1979** [comment]
@terencode There you go. How's that look for you?

**Comment by terencode** [comment]
Looking good! Thanks for your work.
![image](https://user-images.githubusercontent.com/12665563/65837525-c6684600-e2f8-11e9-97dc-2f5fe0cbb2a2.png)

Are playlists only supported for RhythmBox?

**Comment by JasonLG1979** [comment]
RhythmBox has playlist support although they don't emit the signal that tells client's the names have changed so if you change the name of the playlist there's no way for the extension to know it.

GNOME Music has Spotty tracklist support. Cover doesn't work 1/2 the time.

Clementine has playlist support but tracklists are broken.

Pithos is the only player that has a full fully functioning MPRIS implementation as far as I know. But it's a Pandora client so it's not much use out side the US and a couple other countries.

**Comment by JasonLG1979** [comment]
That's why I made the extension "just work" if a feature is supported it will show up if not it is hidden.

**Comment by JasonLG1979** [comment]
Although "Just works" is strictly as far as the user see's. In the extension it took some tinkering to get there. As far as the tracklist and playlist interfaces are concerned it's not that hard. Basically just don't show the widget if there's nothing to show. But volume and the shuffle repeat features require me to poke the bear. Basically when a player shows up I change the property tied to the feature real quick and change it right back and if I get a prop changed signal I know the feature is supported. I also have to pretty fault tolerant. My fallbacks have fallbacks,lol!!!

**Comment by JasonLG1979** [comment]
Really though there's not much incentive for devs to do a full implementation since most clients don't even support all of the player implementation. Spotify's MPRIS implementation is absolute shit for example but you wouldn't know that because it works just fine with most clients. You can get a cover and track info  and you can play, pause, skip back and skip forward but that's about all that works.

**Comment by JasonLG1979** [comment]
btw: I've filed the appropriate bug reports on all the above player. Of them GNOME Music is the only one that is actually working on fixes.

**Comment by terencode** [comment]
It's too bad... Thanks for reporting it.
How do they do it on Windows or Mac?

**Comment by mati865** [comment]
I think MellowPlayer has proper MPRIS implementation. Using it with Deezer allows to fully control position by clicking on the slider, Spotify only reports current position and has basic control.

**Comment by JasonLG1979** [comment]
> How do they do it on Windows or Mac?

I have no idea? Haven't used a Mac in almost 20 years and haven't ran Windows except when I have to at work for over 10 years.

> I think MellowPlayer has proper MPRIS implementation. Using it with Deezer allows to fully control position by clicking on the slider, Spotify only reports current position and has basic control.

Position is a weird property.

1. Position is in microseconds.

2. A property changed signal is not emitted when the Position changes (you wouldn't want a signal every microsecond) unless the player is paused or stopped a client is to assume that playback is progressing normally according to the Rate property. (Rate is a ratio 1.0 = normal speed, 2.0 means 2x speed, 0.5 = 1/2 speed and so on). 

3. Position is read only. To change it you call SetPosition with the trackid and the desired position. But since a lot of players don't implement trackid in metadata SetPosition may not work. You should also not call SetPosition if the CanSeek property is False.

4. When you call SetPosition you can't assume that it actually worked. You have to listen for the Seeked signal. A player should emit Seeked when Position changes in a way that's inconsistent with normal progress in accordance with the Rate property. Either because SetPosition is called or because position was seeked anywhere else. Many players do not emit the Seeked signal when they should and those that do many return stale/invaild new position values.

5. There's an edge case that breaks Position. How is a player supposed to tell a client that a track repeated? Should they send the Seeked signal? Should they set PlaybackStatus to "Stopped" to tell the client to reset the position slider? Should the player assign a new trackid to the track so the client knows to reset the position slider?

Spotify does not emit the Seeked signal when it is supposed to, Position always returns 0 and CanSeek is always False. It does however send a track length in the metadata.

In practice that means that viewing the position in a slider works with Spotify in a MPRIS client so long as you don't seek to a position in the main UI. If you do the position in the MPRIS client's UI will be wrong because Spotify does not emit the Seeked signal.

**Comment by JasonLG1979** [comment]
As far as the edge case in 5. In practice a client should already be keeping track of all that. Ofc is the player is stopped the slider should be stopped and returned to the zero position. If the client gets a Seeked signal the position should be changed to that position. And if the client gets a new trackid the position should be started over at zero. But again many clients do none of the 3 when tracks repeat...

**Comment by terencode** [comment]
Thanks for clarifying Jason. Yeah I asked just in case you knew if the situation was also as bad on other platform :P

**Comment by JasonLG1979** [comment]
@terencode I pushed another bit of tweaks. Could you test it out. I'm thinking if all goes well that I'm going to push this to the gnome extensions site so hopefully it will be approved by the time Ubuntu 19.10 and Fedora 31 are released.

**Comment by terencode** [comment]
The changelog sounds good to me but it won't start: 
```
JS ERROR: TypeError: iconInfo is null
                                                  getSymbolicGiconByName@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:55:5
                                                  _init@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:765:34
                                                  Player@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:923:28
                                                  _init/<@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:1473:39
                                                  _addPlayer/</<@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus.js:438:21
                                                  onProxyReady@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus.js:269:17
                                                  makeProxy/<@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus.js:158:29
```

Otherwise, yes, go for it. it's quite clean now :)

**Comment by JasonLG1979** [comment]
That's strange. How does it look?

**Comment by terencode** [comment]
It doesn't load the extension, or at least nothing is shown on the top bar.

**Comment by JasonLG1979** [comment]
> It doesn't load the extension, or at least nothing is shown on the top bar.

Well that's no good. I don't get any errors on Fedora or Ubuntu. I'll have to check for ```iconInfo``` and fallback to another icon in case it's ```null```.

**Comment by JasonLG1979** [comment]
There you go. It's the best I can do. Basically It tries it's very best to use the bullet icons but will fallback to the arrow icon if it can't.

**Comment by JasonLG1979** [comment]
@terencode Lets try the big hammer approach. Basically I skipped even trying to add the icon to the theme in the textbook fashion and just create a new file icon strictly from the absolute path to the icon. If that doesn't work something is broken.

It should look something like this with the icons all nice and lined up for the most part.
![Screenshot from 2019-10-09 20-19-08](https://user-images.githubusercontent.com/6667703/66532207-279bd080-ead4-11e9-8d5d-c5d68b1d1f16.png)

**Comment by terencode** [comment]
Ok. The extension loads, but no icon at all.

**Comment by JasonLG1979** [comment]
> Ok. The extension loads, but no icon at all.

Are there any errors? This *should* work. Damn it I'm going to have to build an Arch GNOME system in a VM...

**Comment by terencode** [comment]
Nope :/

**Comment by JasonLG1979** [comment]
> Nope :/

Nope as in it doesn't work? Or nope not Arch?

**Comment by terencode** [comment]
Sorry for not being explicit, couldn't find any error in the log and yes I'm on ArchLinux with Plata theme and flat-remix for the icons.

**Comment by JasonLG1979** [comment]
OK let's see if we can figure out if we can get some error info from this.

Find the ```getSymbolicGiconByName``` function in widgets.js
https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/blob/master/mprisindicatorbutton%40JasonLG1979.github.io/widgets.js#L47-L49

and replace it with this:
```js
function getSymbolicGiconByName(name) {
    let gicon = null;
    try {
        let bytes = Gio.File.new_for_path(`${EXT_PATH}/icons/${name}.svg`).load_bytes(null)[0]; 
        gicon = Gio.BytesIcon.new(bytes);
    } catch(e) {
        logError(e);
        gicon = Gio.ThemedIcon.new("pan-end-symbolic");
    }
    return gicon;
}
```

Even if it works it won't display the icon correctly (it won't inherit the color of the icon theme) but if it fails it might help us figure out what's going on.

The problem with Gio.Icons is that they fail silently. The above code actually tries to load the bytes of the file before dumping them into an icon. Hopefully we can catch the error there.

After the copy paste you'll need to reload GNOME Shell to see the difference.

**Comment by JasonLG1979** [comment]
Well I couldn't get any arch based system installed in GNOME Boxes. I've pushed a commit that should at least make it fallback gracefully...

**Comment by terencode** [comment]
I can see the icon this time but too far to the left:

![image](https://user-images.githubusercontent.com/12665563/66688786-5f4b7980-ec88-11e9-8b72-6e507c6e9ffa.png)

Do I still need to try the code you suggested?

**Comment by JasonLG1979** [comment]
> I can see the icon this time but too far to the left:

That means it's falling back.

> Do I still need to try the code you suggested?

It might give us some info.

**Comment by JasonLG1979** [comment]
I'm firing up a fresh Fedora 31 nightly build right now to see if this is related to https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/15

**Comment by terencode** [comment]
I only see the following:
`[mprisindicatorbutton@JasonLG1979.github.io]: EXT_PATH is not defined`

**Comment by JasonLG1979** [comment]
My bad you also have to add:

```js
const EXT_PATH = imports.misc.extensionUtils.getCurrentExtension().path;
```

Up with the rest of the const's.

**Comment by terencode** [comment]
With it: `[mprisindicatorbutton@JasonLG1979.github.io]: Error opening file /usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/icons/current-item-right-symbolic.svg: No such file or directory`

**Comment by terencode** [comment]
Oh I know why, it's a packaging issue. I need to update the PKGBUILD to install your icon...

**Comment by JasonLG1979** [comment]
OK let me know if that solves your issue.

**Comment by JasonLG1979** [comment]
Otherwise I've changed things since that post.

it should be:

```js
        let bytes = Gio.File.new_for_path(`${EXT_PATH}/icons/hicolor/symbolic/apps/${name}.svg`).load_bytes(null)[0];
```

**Comment by JasonLG1979** [comment]
That should let us know if Gio is broken.

**Comment by terencode** [comment]
The original PKGBUILD is pretty convoluted so I just rewrote it from scratch and it seems to work!
![image](https://user-images.githubusercontent.com/12665563/66689814-de42b100-ec8c-11e9-8596-2017d6f109d4.png)

**Comment by JasonLG1979** [comment]
> The original PKGBUILD is pretty convoluted so I just rewrote it from scratch and it seems to work!

Right on all is well then,lol!!!

I know nothing about PKGBUILD. There are no configurations and there's nothing to compile it should basically just be a copy and paste?

**Comment by terencode** [comment]
> I know nothing about PKGBUILD. There are no configurations and there's nothing to compile it should basically just be a copy and paste?

Yep. Check my comment there: https://aur.archlinux.org/packages/gnome-shell-extension-mpris-indicator-button-git/

**Comment by JasonLG1979** [comment]
> Yep. Check my comment there: https://aur.archlinux.org/packages/gnome-shell-extension-mpris-indicator-button-git/

I did that on purpose to make installation easy. Although I'm going to have to add translations one of these days. There are a couple user facing strings now that I added the playlists and tracklist interfaces.

**Comment by terencode** [comment]
Sure, but that will not be hard to package.

**Comment by JasonLG1979** [comment]
I also need to figure out what the extension looks like and how it behaves with left to right languages.

I figure if you're going to do it you might as well do it right as far as accessibility and language support. The problem is that without people that actually use different languages and accessibility features regularly to help me I can only guess. I've never really used the accessibility features in GNOME except out of curiosity to see what they do and I barely read/write English,lol!!!

**Comment by terencode** [comment]
:smile: Just wait for people to open an issue about it and then you got yourself some testers ^^

**Comment by JasonLG1979** [comment]
> Just wait for people to open an issue about it and then you got yourself some testers ^^

Only if that were true. Out of the people that post bug reports very few are willing to help you actually solve the problem. There's a big difference between a user and a consumer. Consumers are starting to out number users these days.

**Comment by terencode** [comment]
Sad.

**Comment by JasonLG1979** [comment]
Oh well. I don't write code for anyone but myself really. If someone finds what I write useful to them, cool. If they want to help me write better code, cool. If they want to fork it and go their own way, cool. I try to be zen about it.

**Comment by JasonLG1979** [comment]
If a consumer comes up here like I <b>HAVE</b> to solve their problem I offer them a full rebate and tell them where to stick it,lol!!!

**Comment by JasonLG1979** [comment]
Hey @terencode I updated the [User Guide](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide) in the wiki in anticipation of a new release. Looking through the code and trying out everything I forgot how much functionality is potentially exposed,lol!!! I know it's overkill but it's concise,lol!!! Give it a look and tell me what you think if you would please.

**Comment by terencode** [comment]
Hey @JasonLG1979 it's really well done :+1: and shows how polished the extensions is.
Two remarks: 
- https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/Known-Player-Bugs#gnome-music The issue was fixed so you can remove this entry.

- Intuitively, I would think mouse wheel up would go to the next track and not the previous one.

**Comment by JasonLG1979** [comment]
> * https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/Known-Player-Bugs#gnome-music The issue was fixed so you can remove this entry.

Last I checked it still wasn't 100% fixed. I'll Check again. I don't use GNOME Music on a regular basis.

> * Intuitively, I would think mouse wheel up would go to the next track and not the previous one.

Think of it as scrolling down though a playlist. Scrolling down gets you to the next track scrolling would get you to the previous track.

**Comment by terencode** [comment]
> Last I checked it still wasn't 100% fixed. I'll Check again. I don't use GNOME Music on a regular basis.

I only saw the issue was closed and I am also not using it. 

>Think of it as scrolling down though a playlist. Scrolling down gets you to the next track scrolling up would get you to the previous track.

Ok makes sense. Would it be possible to add vertical scroling as well?

**Comment by JasonLG1979** [comment]
> Ok makes sense. Would it be possible to add vertical scrolling as well?

What would you have in mind? We can for sure talk about what vertical scrolling could do to in each section. I think I have a bluetooth mouse that does vertical scrolling to test with?

**Comment by terencode** [comment]
My mouse also have vertical scrolling. I was thinking volume up/down for horizontal scrolling and previous/next with the vertical one to begin with.

**Comment by JasonLG1979** [comment]
> My mouse also have vertical scrolling. I was thinking volume up/down for horizontal scrolling and previous/next with the vertical one to begin with.

We could add vertical scrolling volume controls to the indicator icon and the player section. Those seem like reasonable places to start with that. I *think* the volume section might already have scrolling volume control already. for the volume control section control wise it's exactly like system volume control with the addition of a mute toggle. I pretty much copied what the Shell has and modified it for my needs.

**Comment by JasonLG1979** [comment]
Duh. I mean horizontal(left to right) everywhere above. Not vertical (up and down). Yes we can add <b>horizontal</b> scrolling for volume control.

**Comment by terencode** [comment]
Lol same I meant vertical for up/down and horizontal for previous/next, which makes more sense to me.

**Comment by JasonLG1979** [comment]
There try master now. https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/commit/7ecf0d3ac983a0928914500fe390c7f7ddeba949 should add volume mouse actions to the indicator icon the player section and the media controls section. Give that a try. Left = volDown, Right = volUp.

**Comment by JasonLG1979** [comment]
> Lol same I meant vertical for up/down and horizontal for previous/next, which makes more sense to me.

I kept up/down as prev/next and made volume left/right because next/prev is a more basic feature then volume and not every mouse has left/right scrolling so it seemed to make sense to group the less likely feature with the less likely mouse direction.

**Comment by JasonLG1979** [comment]
Now I just need someone with a touch screen to help me test touch integration. At the very least I think can emulate secondary mouse button clicks with a touch hold. I've seen it down in code but I have no idea if it actually works. I do not have a touch screen, nor have I ever ran GNOME on a touch screen.

**Comment by terencode** [comment]
> I kept up/down as prev/next and made volume left/right because next/prev is a more basic feature
Ok makes sense.

I also can't help you for the touchscreen part.

**Comment by JasonLG1979** [comment]
> I also can't help you for the touchscreen part.

That kinda like the accessibility and right to left language stuff. I can copy other people's code but I really can't test it. I suppose if someone wants the features they can help me out if not oh well it doesn't affect me.
