### ISSUE TITLE
Doesn't work in Gnome Shell 3.34

### ISSUE THREAD

**Issue by mati865** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#13]
## Distro Name & Version
Arch Linux (rolling)
## GNOME Shell Version
3.34
## Other Installed Extensions

Default extensions, Freon, Gsconnect, TopIcons Plus, 
## Expected Behavior

Working just like in Gnome 3.32.
## Current Behavior

Icon doesn't show at all.
## Detailed Description

Since I upgraded to Gnome 3.34 this extension and [TopIcons Plus](https://github.com/phocean/TopIcons-plus/pull/128) stopped working. Disabling TopIcons Plus doesn't help.

**Comment by JasonLG1979** [comment]
I know. Gnome 3.34 just came out. 3.34 will break a lot of extensions as they have pretty much GObject'd all of the pre-made widget classes finally. I am unaware of any non-rolling distros that currently feature Gnome 3.34 in their stable versions. see https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/12

My plan is that as soon as 3.34 proper hits the Ubuntu 19.10 daily is to fire it up in a VM and fix all the breaks.

**Comment by JasonLG1979** [comment]
The Ubuntu 19.10 daily is pretty much garbage atm. 3.34 is in Fedora 31 now though. I downloaded the beta and thew it in a VM. It took a little bit to get the extension in a working state. I love those stable API's... Anyway, you can expect 3.34 support in about a month or so.

**Comment by mati865** [comment]
Thank you.
I'm considering going back to KDE though because there are still few other important extensions broken.

**Comment by coxackie** [comment]
I am not entirely sure this is only a problem of the extension. Info is not even shown in the notification area - when I play songs from Rhythmbox or GNOME music, there is nothing coming up.

**Comment by JasonLG1979** [comment]
> I'm considering going back to KDE though because there are still few other important extensions broken.

I switched to KDE for a couple years back when GNOME Shell 1st came out. KDE is a fine desktop.

> I am not entirely sure this is only a problem of the extension. Info is not even shown in the notification area - when I play songs from Rhythmbox or GNOME music, there is nothing coming up.

Couldn't tell you? I'll fire up my VM and see what's going on. And can say that the reason this extension doesn't work as is is because of A LOT of internal changes in the stock widgets. After adding the newly required boilerplate code to inherent from GObjects in Gjs and a few other tweaks it works.

**Comment by coxackie** [comment]
Thanks - if you do get it to work, could you make a separate branch with the changes so we can check it?

**Comment by JasonLG1979** [comment]
A bit of fun testing in Fedora 31. Gio basically doesn't work at all on non-local files when used in the Shell. resulting in no album art for players that send non-local urls as cover art urls, like Spotify. This effects both this extension and the default MPRIS implementation.

Judging from this Arch bug https://bugs.archlinux.org/task/62860 it appears to be a build issue as ```# setcap -r /usr/bin/gnome-shell``` and restarting the shell magically makes the issue go away. I'm unsure of how much of a security issue that command creates so I would not recommend anyone using it. In my case I'm working off a disposable VM strictly for testing the extension so it really doesn't matter.

I will check upstream to see if they know about it yet.

**Comment by coxackie** [comment]
ok - thanks. Let me mention that also local files do not seem to work - when I play from my local music library, for example, it does not show in the shell MPRIS implementation.

**Comment by JasonLG1979** [comment]
> ok - thanks. Let me mention that also local files do not seem to work - when I play from my local music library, for example, it does not show in the shell MPRIS implementation.

So you're running Fedora 31 then? Strange. What player? Do you know where the cover images are?

**Comment by JasonLG1979** [comment]
[D-Feet](https://wiki.gnome.org/Apps/DFeet) is great for snooping around in DBus. With it, among other things, you can see what players are sending as metadata, specifically ```mpris:artUrl``` in this case.  It's one of my go to's to seeing what's going on with potentially misbehaving players.

Although to be fair just because the music is local that doesn't mean the cover art is local.

I use Pithos a lot to test features because it implements all of the MPRIS interfaces and I know they are done correctly because I wrote them,lol. Anyway in Pithos covers are temporarily cached locally and then that local file url is sent to MPRIS. As apposed to a player like Spotify that sends a https url so that every time the metadata changes slow I/O has to be done. Not to mention the waste of network bandwidth.

Ideally all players would cache images locally if they are remote.

**Comment by coxackie** [comment]
> > ok - thanks. Let me mention that also local files do not seem to work - when I play from my local music library, for example, it does not show in the shell MPRIS implementation.
> 
> So you're running Fedora 31 then? Strange. What player? Do you know where the cover images are?

No, I am running Arch. i tried GNOME Music, Rhythmbox, Lollypop, none of them shows up in the shell MPRIS implementation (notification area). The extension also does not work. This happened exactly after the update to 3.34.

**Comment by JasonLG1979** [comment]
Well from what little I understand of setcap it deals with the extended attributes of the actual executable binary file, so this does not really appear to be a GNOME Shell bug. It looks like a bug in regards to how the binaries are built. Although I guess if the default build params cause this then maybe it is a GNOME bug? I don't really know for sure it's a little out of my wheelhouse.

**Comment by mati865** [comment]
> I switched to KDE for a couple years back when GNOME Shell 1st came out. KDE is a fine desktop.

I was using KDE SC since around 4.3 but Plasma 5 didn't play very well with proprietary Nvidia GPU. Saw recent kwin commits and I hope it will work at least as good as Gnome.

**Comment by JasonLG1979** [comment]
> I was using KDE SC since around 4.3 but Plasma 5 didn't play very well with proprietary Nvidia GPU. Saw recent kwin commits and I hope it will work at least as good as Gnome.

The later 4.x releases where rock solid for me. The early days of Plasma 5 are what made me switch back to GNOME.

**Comment by JasonLG1979** [comment]
> The extension also does not work. This happened exactly after the update to 3.34.

Gio not working and this extension not working in 3.34 are unrelated. True Gio not working causes the cover art to not work correctly but the reason this extension is not yet compatible at all with 3.34 is that they have moved from composition to inheriting as far as the main stock widgets. Before the stock widgets were just plain JavaScript classes with ```this.actor``` inside the class being the actual GObject so you could extend the class just like you would a normal JavaScript to inherit from it and to do anything you'd need to do ```stockWidget.actor.doStuff()``` now 99% of them are actual GObjects. That means that to extend/inherit from them requires a little extra boilerplate code. But it also means that you can just do ```stockWidget.doStuff()``` and when extending all the GObject goodies are available so it has an upside for sure.

**Comment by coxackie** [comment]
This all is a bit out of my zone of comprehension at this point (hopefully not in the future). However, as I said, if you find a way to make the extension work and create a new branch, I will be happy to test it. At least you will know how it performs on Arch with GNOME 3.34.

**Comment by JasonLG1979** [comment]
> This all is a bit out of my zone of comprehension at this point

Me too. I learn as I go. There is no GNOME Shell extension API and very little to no useful docs. Basically when things don't turn out the way I expect them to I end up reading the GNOME Shell source code to see what they broke.

> However, as I said, if you find a way to make the extension work and create a new branch, I will be happy to test it. At least you will know how it performs on Arch with GNOME 3.34.

With the exception of Gio being broken I have a working version I'm working on still. It's ugly and I'm not sure how I want to go in a few places atm so I'd rather not push anything right now. When I iron a few more things out I'll just push it to master. Basically master is a rolling testing version. Proper releases that I upload to the extensions site are basically just working snapshots.

**Comment by JasonLG1979** [comment]
@coxackie I'm going to push something tomorrow for people to start testing. It works for me in Fedora 31 and Ubuntu 19.10 VM's so I imagine it should work just fine in Arch also.

**Comment by coxackie** [comment]
Thanks a lot - I will pull and let you know how it looks.

**Comment by JasonLG1979** [comment]
@coxackie there you go. https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/commit/69581f1459e4083110d9ccab5343673b33b465aa introduces a metric shit ton of changes test away,lol!!!

**Comment by JasonLG1979** [comment]
Sorry it took longer then I expected. I ran into another issue. Using the gjs DBus Proxy helper functions to call the mpris Quit method caused errors with some players. I finally just said piss on and just side stepped the helper and called Quit directly. Bingo no errors.


https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/blob/master/mprisindicatorbutton%40JasonLG1979.github.io/dbus.js#L1484-L1498

**Comment by coxackie** [comment]
already testing - no problem so far, works as expected. many thanks!

**Comment by JasonLG1979** [comment]
> already testing - no problem so far, works as expected. many thanks!

I will also ofc continue to test it and tweak it if/as needed. As I have said before I will push an update to the extension site round about the time of the Ubuntu 19.10 and Fedora 31 releases.

**Comment by terencode** [comment]
This is shown when disabling the extension:
```
JS ERROR: Exception in callback for signal: destroy: TypeError: this._appWrapper is null
                                                  destroy@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus.js:1907:13
                                                  Player/destroyId<@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:953:17
                                                  _emit@resource:///org/gnome/gjs/modules/signals.js:135:27
                                                  destroy@resource:///org/gnome/shell/ui/popupMenu.js:769:9
                                                  removeAll@resource:///org/gnome/shell/ui/popupMenu.js:753:13
                                                  destroy@resource:///org/gnome/shell/ui/popupMenu.js:766:9
                                                  destroy@resource:///org/gnome/shell/ui/popupMenu.js:906:9
                                                  _onDestroy@resource:///org/gnome/shell/ui/panelMenu.js:192:13
                                                  disable@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/extension.js:43:9
                                                  _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:78:13
                                                  _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:406:13
                                                  _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:403:9
```
And this is spammed when clicking on the indicator button:
```
sept. 26 13:37:32 terence-arch gnome-shell[1609]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
sept. 26 13:37:32 terence-arch gnome-shell[1609]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
sept. 26 13:37:32 terence-arch gnome-shell[1609]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
sept. 26 13:37:32 terence-arch gnome-shell[1609]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
sept. 26 13:37:32 terence-arch gnome-shell[1609]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
sept. 26 13:37:32 terence-arch gnome-shell[1609]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
sept. 26 13:37:32 terence-arch gnome-shell[1609]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
sept. 26 13:37:32 terence-arch gnome-shell[1609]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
```

**Comment by JasonLG1979** [comment]
@terencode the latest commit should fix the ```JS ERROR``` as far as the log spamming I'll need to dig a little deeper but it has to do with CSS parsing

https://github.com/GNOME/libcroco/blob/master/src/cr-parser.c

**Comment by JasonLG1979** [comment]
@terencode I think I fixed the log spamming also.

**Comment by terencode** [comment]
@JasonLG1979 very well done! Both issues fixed.

**Comment by JasonLG1979** [comment]
@coxackie I pushed some new code. Give it a test and let me know what you think.

**Comment by coxackie** [comment]
Testing it. All good up to now. Thanks!

**Comment by terencode** [comment]
We can probably close this issue now?

**Comment by JasonLG1979** [comment]
> We can probably close this issue now?

I'm going to art a new issue to continue to investigate why custom icons can not be added or used as they are supposed to be.

**Comment by terencode** [comment]
Makes sense. Count on me to help you debug it.

**Comment by JasonLG1979** [comment]
The master branch seems to be in good shape. I've uploaded a version for 3.34 to the extensions site. It should show up when they approve it.

**Comment by JasonLG1979** [comment]
Also, please have a look at the [User Guide](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide) as a lot more potential functionality has been exposed.

**Comment by sabian2008** [comment]
Hi, sorry for necrothreading. If I understand the thread correctly, you couldn't fix the Spotify issue, right? Even though no album information is displayed (nor song, nor album, nor media controls), shouldn't the mouse gestures (e.g. middle click in the icon) work anyway? That's not the case for me currently.

I am using Fedora from flathub, in Fedora 31. Extension works as expected when using, for example, VLC. The extension + flatpak was working in F30 though.
