### ISSUE TITLE
Do not show indicator when there is nothing to control

### ISSUE THREAD

**Issue by Esokrates** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#14]
I am taking chromium as an example here: As soon as chromium is started the indicator button is shown, although there is not yet anything to control, as I don't have an tab playing audio open yet.

![Screenshot from 2019-09-20 20-19-57](https://user-images.githubusercontent.com/17780185/65349740-74327100-dbe4-11e9-984d-56827ff8fcf0.png)

It would be great if the indicator button would only show up, if there is actually something to control, when all buttons are grayed out, it should not be visible.

**Comment by JasonLG1979** [comment]
That's not the fault of this extension. See https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/10 and https://gitlab.gnome.org/GNOME/gnome-shell/issues/1362
