### ISSUE TITLE
GObject.registerClass() error on Gnome 3.32.1

### ISSUE THREAD

**Issue by alexandrupetrini** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#17]
Hi, 
The indicator does not appear in Ubuntu 19.04 with Gnome 3.32.1 vanilla. I get:
> TypeError: GObject.registerClass() used with invalid base class (is PopupBaseMenuItem).

![2019-10-26_22-22](https://user-images.githubusercontent.com/44755709/67625029-538fb380-f841-11e9-9142-5d31881cb3f2.png)

This happened when I updated to the latest version from [https://extensions.gnome.org/extension/1379/mpris-indicator-button/](https://extensions.gnome.org/extension/1379/mpris-indicator-button/)

Both versions 10 and 11 have same error.

**Comment by JasonLG1979** [comment]
Versions 10 and 11 are not supported on GNOME 3.32.

https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/Bug-Reports-and-Feature-Requests#bug-reports
