### ISSUE TITLE
Extension won't turn on

### ISSUE THREAD

**Issue by jikamens** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#22]
**Describe the bug**

This is what I see in the journalctl log after installing the extension into GNOME Shell 3.34 via extensions.gnome.org:

```
Nov 06 13:13:24 jik-d42-x1 gnome-software[2200]: State change on user/*/*/shell-extension/mprisindicatorbutton_JasonLG1979.github.io/* from available to installed is not OK
```

I tried downloading and installing by hand and it doesn't work then either.

When I go to the main extensions.gnome.org page the add-on shows up as being installed and off. If I click the toggle button to turn it on, the toggle turns to on, but when I reload the page, it's off again. Nothing shows up in the journalctl log when I do that.

**Steps To Reproduce:**

Try to install the extension in GNOME Shell 3.34 on Ubuntu 19.10.

**Expected behavior**

It should work.

**System Details (please complete the following information):**

 - **Extension version:** 12
 - **Installed from:** extensions.gnome.org
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Ubuntu 19.10
 - **List of other installed and enabled Extensions***

```
jik@jik-d42-x1:~$ gnome-extensions list --enabled
desktop-icons@csoriano
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com
```

**Comment by JasonLG1979** [comment]
After you flip the switch and click install is there a ```mprisindicatorbutton@JasonLG1979.github.io``` folder in  ```~/.local/share/gnome-shell/extensions```?

**Comment by JasonLG1979** [comment]
Another question:
The other extension you list are the default system wide extension installed by default in Ubuntu. Have you had any issues installing other extensions from the extensions site.

**Comment by JasonLG1979** [comment]
> I tried downloading and installing by hand and it doesn't work then either.

By that you mean extracting the zip to ```~/.local/share/gnome-shell/extensions```? When install an extension manually like that you'll need to restart GNOME Shell for it to pickup on the fact that there's a new extension.

In X you can restart GNOME Shell by pressing Alt+F2, once you get a prompt enter an "r" (no quotes) and then press ENTER.

In Wayland you'll need to logout and then back in.

You can then either use Tweaks (if you have it installed?) or ```gnome-shell-extension-prefs``` to enable/disable it and not even mess with the site.

**Comment by jikamens** [comment]
> The other extension you list are the default system wide extension installed in Ubuntu. Have you had any issues installing other extensions from the extensions site?

Interesting. I just tried three other extensions that claim to be compatible with 3.34 and none of them worked either. A GNOME Shell bug, I guess? If so, then probably not your fault. I will try to chase that down elsewhere.

**Comment by jikamens** [comment]
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1851554

**Comment by JasonLG1979** [comment]
Are you behind any kind of firewall or proxy?

**Comment by JasonLG1979** [comment]
I know you tried downloading and extracting the extension. Have you tried enabling it with ```gnome-shell-extension-prefs```? And not even suing the website at all. It sounds more like an issue with the site and/or the browser plugin bits then anything to me.

**Comment by jikamens** [comment]
> Are you behind any kind of firewall or proxy?

No.


> I know you tried downloading and extracting the extension. Have you tried enabling it with `gnome-shell-extension-prefs`? And not even using the website at all. It sounds more like an issue with the site and/or the browser plugin bits then anything to me.

Yes.

**Comment by JasonLG1979** [comment]
Weird. If you downloaded the zip and extracted to ```~/.local/share/gnome-shell/extensions``` restarted GNOME shell and used ```shell-extension-prefs``` to enable it it should work.

OK stupid question what are the contents of the zip you downloaded?

**Comment by jikamens** [comment]
> Weird. If you downloaded the zip and extracted to `~/.local/share/gnome-shell/extensions` restarted GNOME shell and used `shell-extension-prefs` to enable it it should work.

I know it should.

It doesn't.

That's the problem.

> OK stupid question what are the contents of the zip you downloaded?

[mprisindicatorbuttonJasonLG1979.github.io.v12.shell-extension.zip](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/files/3816582/mprisindicatorbuttonJasonLG1979.github.io.v12.shell-extension.zip)

**Comment by JasonLG1979** [comment]
Well they mangled the name of the zip.

If you extract that as is it won't work because it will extract it as ```mprisindicatorbuttonJasonLG1979.github.io.v12.shell-extension``` which will cause the extention to not load because the folder name doesn't match the UUID in ```metadata.json``` the folder containing the extension has to match the UUID in this case ``` mprisindicatorbutton@JasonLG1979.github.io```

**Comment by jikamens** [comment]
I know that. I didn't create it in a directory named after the Zip. I created it in a directory called "mprisindicatorbutton@JasonLG1979.github.io". That's not the problem.

Does this match what you see on your computer?

```
jik@jik-d42-x1:~/.local/share/gnome-shell/extensions$ find mprisindicatorbutton@JasonLG1979.github.io -type f | sort | xargs sum
12146    66 mprisindicatorbutton@JasonLG1979.github.io/dbus.js
64991     3 mprisindicatorbutton@JasonLG1979.github.io/extension.js
33096     2 mprisindicatorbutton@JasonLG1979.github.io/icons/hicolor/symbolic/apps/current-item-left-symbolic.svg
32046     2 mprisindicatorbutton@JasonLG1979.github.io/icons/hicolor/symbolic/apps/current-item-right-symbolic.svg
27313    18 mprisindicatorbutton@JasonLG1979.github.io/indicatorToolTip.js
36316     1 mprisindicatorbutton@JasonLG1979.github.io/metadata.json
14284     1 mprisindicatorbutton@JasonLG1979.github.io/stylesheet.css
28951    51 mprisindicatorbutton@JasonLG1979.github.io/widgets.js
```

**Comment by jikamens** [comment]
I appreciate that you are trying to help, but I need to ask you to understand that I have been working in software engineering since 1985. My first Linux distribution was Slackware 1.0. There were years early on in the history of Red Hat Linux when I submitted more bugs to Red Hat's bugzilla than anyone else. I know what I'm doing. The problem here is not that I made some stupid error.

**Comment by JasonLG1979** [comment]
OK well, just trying to cover the bases. You're the guy that reported a bug 1st though the extensions site when the github page is clearly listed and then opened a bug here without testing to see if you couldn't reproduce the bug with other extensions. Seems like pretty amateur moves to me there Super Linux Man. Good luck getting any help with that attitude and behavior mix.

**Comment by JasonLG1979** [comment]
For future reference a less douchey response might sound more like this:

*"Yep, that's all good, done that and it still doesn't work."*

Throwing out you're l33t cred just makes you look like an ass.
