### ISSUE TITLE
Song not updated

### ISSUE THREAD

**Issue by real-or-random** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#25]
**Describe the bug**

Song not updated. Only reloading the extension will show the new song.

**Steps To Reproduce:**

1. Change song

**Expected behavior**
New song shown. 

**System Details (please complete the following information):**

 - **Extension version:** https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/commit/336d0fe5c6cbb62b583634e49fae573d7992ec38
 - **Installed from:** Arch AUR / git
 - **GNOME/Shell version:** 3.34.2
 - **Distro/Release:** Arch
 - **List of other installed and enabled Extensions***

What can I do to debug this?

**Comment by real-or-random** [comment]
nevermind, this is https://github.com/Spotifyd/spotifyd/issues/457

**Comment by JasonLG1979** [comment]
> What can I do to debug this?

I have no experience with RUST but I've commented on that issue and given a bit of advise in regards to MPRIS properties.

I know the MPRIS spec pretty well and more important know how the different properties "interact and overlap" and am happy to act as an interpreter of sorts. But it's up to them though, they can take it or leave it.
