### ISSUE TITLE
Enlarged album cover.

### ISSUE THREAD

**Issue by Mishlem** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#26]
**Requesting a function:**
It would be nice if, when you hover over the album / track icon, an enlarged cover is shown.
![https://i.imgur.com/oT8vIjs.jpg](https://i.imgur.com/oT8vIjs.jpg)

**Comment by JasonLG1979** [comment]
That's a lot of extra code complexity and work just for a little eye candy. Really if you want to see a larger version of the cover you could just focus the player. (as in the image you posted)

I'm not really sold on the idea.

It's not really something that I'm interested in pursuing but if you'd like to put in the work and put in a pull request I'd look at it.

**Comment by JasonLG1979** [comment]
I'm going to close this issue for now @Mishlem but in future if you decide you'd like to try your hand a pull request I'd be willing to give it a look.
