### ISSUE TITLE
Reanimate gnome-shell-extensions-mediaplayer for gnome 3.34

### ISSUE THREAD

**Issue by Mishlem** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#27]
Hello.

The gnome-shell-extensions-mediaplayer project is in the archive and I can’t leave the issue there, so I give a request here.

I understand that you are tired of supporting gnome-shell-extensions-mediaplayer, but I want to ask you to reanimate it for gnome 3.34.

No doubt gnome-shell-extension-mpris-indicator-button is a good plugin, but sometimes gnome-shell-extensions-mediaplayer does exactly what need.

I am ashamed to ask you to do this, but if I knew javascript and GJS well, I would do it myself.

**Comment by JasonLG1979** [comment]
> but if I knew javascript and GJS well, I would do it myself.

Then learn it. No one taught me anything. All I know about javascript and GJS is though a combination of Googling stuff, looking at other's source code and trial and error.

**Comment by JasonLG1979** [comment]
For general JavaScript docs a good source is https://developer.mozilla.org/en-US/docs/Web/JavaScript

GJS really doesn't have any good complete docs that I know of. I generally just use the docs for the Python bindings as a reference and from there a lot of trial and error. For the most part things work about the same though. Basically you just have to allow for js syntax and convention. For example ```None``` in Python is basically ```null``` in JavaScript and so on.

https://lazka.github.io/pgi-docs
