### ISSUE TITLE
On the google-chrome: 79.0.3945.130 control buttons are gone.

### ISSUE THREAD

**Issue by webmastak** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#28]
**Describe the bug**

On the **google-chrome:** 79.0.3945.130 control buttons are gone:
![https://i.imgur.com/UfIonOA.png](https://i.imgur.com/UfIonOA.png)
The built-in mpris control also appeared.
Single video:
![https://i.imgur.com/c91jxYG.png](https://i.imgur.com/c91jxYG.png)
Playlist:
![https://i.imgur.com/xL31Oco.png](https://i.imgur.com/xL31Oco.png)
Allows you to not only switch tracks (only when playing a playlist), but also has scroll buttons on the track.

With **google-chrome**: 78.0.3904.70 and below everything is fine:
![https://i.imgur.com/6ptinWf.png](https://i.imgur.com/6ptinWf.png)

**System Details:**

 - **Extension version:** master
 - **Installed from:** GitHub
 - **GNOME/Shell version:** 3.34.2
 - **Distro/Release:** Manjaro

**Comment by JasonLG1979** [comment]
Chrome's MPRIS implementation is broken. Most of the properties are non-existent. In this particular case [CanControl](https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:CanControl) is either false or non-existent. If CanControl is false or non-existent then the controls are hidden.

**Comment by webmastak** [comment]
You can do then do not show mpris-indicator-button if the player is Chrome?

**Comment by JasonLG1979** [comment]
> You can do then do not show mpris-indicator-button if the player is Chrome?
> Because with Chrome and Chromium, it has become useless.
> 
> I have with Vivaldi: 2.10.1745.27, and he is on Chromium as well.

I'm a Chrome user also. I have been meaning to workaround it.

By spec that property is not expected to change so an option is to just ignore players altogether that lack the property or if it is false. I really don't want to do any blacklisting.

**Comment by webmastak** [comment]
> so an option is to just ignore players altogether that lack the property or if it is false.
And this will prevent the button from showing if one Chrome player?

**Comment by JasonLG1979** [comment]
> And this will prevent the button from showing if one Chrome player?

Yes, instead of just hiding the controls the whole player will be ignored and hidden.

**Comment by webmastak** [comment]
It’s just that in Chrome, if you close the player’s tab, the button still remains and you have to restart the Gnome Shell so that it disappears.

**Comment by JasonLG1979** [comment]
> It’s just that in Chrome, if you close the player’s tab, the button still remains and you have to restart the Gnome Shell so that it disappears.

Chrome puts up and interface when something plays and never takes down. In my case if you quit Chrome it goes away.

**Comment by webmastak** [comment]
> if you quit Chrome it goes away.

Yes, that’s what I wrote above, but it’s not convenient.

**Comment by JasonLG1979** [comment]
> Yes, that’s what I wrote above, but it’s not convenient.

Sorry my bad,lol!!! No it's not, but that's not my bug.

**Comment by webmastak** [comment]
Hands did not reach the fork of the mediaplayer extension, I will wait for the mpris-indicator-button fix. )

**Comment by JasonLG1979** [comment]
Their implementation is absolute shit. For example most of the time I can fire up d-feet to quickly and easily figure out what a player is doing but since they don't even do the absolute most basic thing when it comes to any dbus interface which is make it introspectable. So if I want to see what's actually going on I have to put in a bunch of logging in the extension.

**Comment by JasonLG1979** [comment]
> Hands did not reach the fork of the mediaplayer extension, I will wait for the mpris-indicator-button fix with Chrome. )

I'll have something maybe tonight if not in a couple days at most.

**Comment by webmastak** [comment]
Interesting in **[argos](https://github.com/p-e-w/argos)** with my modification of mpris.1.1s.sh in Chrome, everything works and play / pause and switch tracks if from the playlist.

Did this:
`dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep 'org.mpris.MediaPlayer2.'`
I get: string "org.mpris.MediaPlayer2.chrome.instance24238"

`~/.config/argos/mpris.1.1s.sh`
```
#!/usr/bin/env bash

PLAYERS=$(dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep 'org.mpris.MediaPlayer2.' | grep -E 'auryo|rhythmbox|Lollypop|chrome.instance24238')
CUTENT_PLAYER=$(echo "$PLAYERS" | cut -d '"' -f 2 | head -1)
COMMAND_BASE="dbus-send --print-reply --dest=$CUTENT_PLAYER /org/mpris/MediaPlayer2"
PLAY_PAUSE="$COMMAND_BASE org.mpris.MediaPlayer2.Player.PlayPause"
NEXT="$COMMAND_BASE org.mpris.MediaPlayer2.Player.Next"
PREVIOUS="$COMMAND_BASE org.mpris.MediaPlayer2.Player.Previous"

MPRIS_META=$($COMMAND_BASE org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata)
ARTIST=$(echo "$MPRIS_META" | sed -n '/artist/{n;n;p}' | cut -d '"' -f 2 | cut -c1-30)
SONG_TITLE=$(echo "$MPRIS_META" | sed -n '/title/{n;p}' | cut -d '"' -f 2 | cut -c1-30)
ART_URL=$(echo "$MPRIS_META" | sed -n '/artUrl/{n;p}' | cut -d '"' -f 2)

SONG_TITLE=${SONG_TITLE//&/&#38;}
SONG_TITLE=${SONG_TITLE//|/&#124;}
ARTIST=${ARTIST//&/&#38;}
ARTIST=${ARTIST//|/&#124;}

if [[ "$CUTENT_PLAYER" == *"auryo"* ]]; then 
  player='auryo'
  icon='multimedia-audio-player-symbolic'
elif [[ "$CUTENT_PLAYER" == *"rhythmbox"* ]]; then	
  player='rhythmbox'
  icon='rhythmbox-notplaying'
else 
  player='lollypop'
  icon='org.gnome.Lollypop-symbolic'
fi

if [[ "$ART_URL" == *file://* ]]; then 
  base64img=$(base64 -w 0 < "${ART_URL//file:///}")
else
  base64img=$(curl -s "${ART_URL//large/t200x200}" | base64 -w 0)
fi

PLAYBACK_STATUS=$($COMMAND_BASE org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:PlaybackStatus)
if [[ $PLAYBACK_STATUS == *"Playing"* ]]; then
  TITLE="| iconName=media-playback-start"
  PLAY_PAUSE_TOGGLE="Pause | iconName=media-playback-pause bash='$PLAY_PAUSE' terminal=false refresh=true"
elif [[ $PLAYBACK_STATUS == *"Paused"* ]]; then
  TITLE="| iconName=media-playback-pause"
  PLAY_PAUSE_TOGGLE="Play | iconName=media-playback-start bash='$PLAY_PAUSE' terminal=false refresh=true"
else
  TITLE="| iconName=$icon" 
  PLAY_PAUSE_TOGGLE="Play | iconName=media-playback-start bash='$PLAY_PAUSE' terminal=false refresh=true"
fi

if [ "$PLAYERS" == "" ]; then echo "---"; fi
echo "$TITLE"
echo "---"
if [ "$base64img" != "" ]; then echo "| image=$base64img imageWidth=200 imageHeight=200 terminal=false"; fi
if [ "$SONG_TITLE" != "" ]; then echo "<b>$SONG_TITLE</b>"; fi
if [ "$ARTIST" != "" ]; then echo "$ARTIST"; fi
if [ "$SONG_TITLE" != "" ] && [ "$ARTIST" != "" ]; then echo "---"; fi
echo "$PLAY_PAUSE_TOGGLE"
echo "Next | iconName=media-skip-forward bash='$NEXT' terminal=false refresh=true"
echo "Previous | iconName=media-skip-backward bash='$PREVIOUS' terminal=false refresh=true"
if [[ $player == *"rhythmbox"* ]]; then 
  echo "Show | iconName='$icon' bash='$player' terminal=false"
  echo "Quit | iconName=window-close bash='pkill $player' terminal=false"
fi

```

**Comment by JasonLG1979** [comment]
> I think that for Chrome with their integrated mpris control this is no longer needed

Like I said their implementation is broken. A bunch of other stuff is broken also. Last I checked none of the "can" props actually worked. Play, pause, next and whatnot may still work but the can props are used to tell you what functionality to expose. Again this is not my bug. I'm pretty forgiving when it comes to the spec and I do a pretty good job, I think, of gracefully exposing and hiding features based on what the player says that it supports. I can only do so much. The extension reads all of the properties and decides what to expose based on those properties if a player doesn't even bother to do the bare minimum it's not my problem. It's the player's bug.

**Comment by JasonLG1979** [comment]
There are really 2 options.

1. Completely ignore a player who's canControl property is not true and not even add it at all to the list of players.

2. Treat canControl as a visible toggle for the player in menu so that if it did change to true it would show up.

In either case until Chrome fixes their shit implementation it wouldn't show up in the extension.

**Comment by webmastak** [comment]
> There are really 2 options.

I think it’s worthwhile to apply the first option.

**Comment by JasonLG1979** [comment]
> I think Chrome will not fix it because they implemented the built-in functionality for managing mpris.

I don't even know if that's mpris?

> So it’s worth applying the first option.

My concern is that other players may also set canControl at least initially to false also. The video player Celluloid does in the short list of players I've tested so far.

> I liked the scroll buttons on the track, in Chrome built-in functionality for managing mpris.
> This can be implemented in mpris-indicator-button?

What does it do? Scrolling already does stuff in the extension. There is a lot of mouse wheel and keyboard shortcuts.

https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide

**Comment by webmastak** [comment]
> What does it do?

This is similar to Position Slider, only with the help of buttons, when pressed, moves accelerated along the track forward or backward.

**Comment by JasonLG1979** [comment]
> This is similar to Position Slider, only with the help of buttons, when pressed, moves accelerated along the track forward or backward.

Oh, I thought you were talking about the mouse wheel scroll buttons. Nope, there is no plans to enable any sort of seeking. that's goes back to the whole position slider thing.

> I don’t even know, but for some reason they broke mpris.
> Using the `chrome://flags/#global-media-controls` turns on if disable.

Yep, I know.

> I noticed in Rhythmbox, if you do Raise / Minimize Toggle and it is minimized using the [Tray Icon](https://github.com/palfrey/rhythmbox-tray-icon) plugin (which minimizes the Rhythmbox if you close it), when I do Raise, the spinner at the mouse cursor spins for a long time.

I don't use Rhythmbox nor that plugin. By default Rhythmbox has pretty reasonable behavior. If something is playing and you close the window it hides if nothing is playing it quits. I'm not really sure why you'd need a tray icon plugin with the combination of that behavior and mpris desktop integration?

If Rhythmbox is in the menu that means that the MPRIS interface is still up.

Raising in this extension works like this:

If a window is present it directly activates that window, otherwise if there is no window but a shellApp for the player it activates the shellApp, which basically has the same affect. Otherwise if there is no window and no shellApp and the player's canRaise property is true the mpris raise method is called. If there is no window, no shellApp and canRaise is false or non-existent nothing is done.

**Comment by webmastak** [comment]
I can’t figure out how to make it so that if `canControl = false `do not show the player if there are several or do not show mpris-indicator-button if there is only one player. 

I wanted to quickly make a hack, it didn’t work out. (

**Comment by JasonLG1979** [comment]
> You could tell how to do it?

I'm working on it. My solution so far is to ignore any player that's canControl property is not true. When I say ignore I mean totally reject it really, as in don't add it to the menu, throw an error logging message and ban it for that session (technically as long as the extension is enabled during that session. Disabling and re-enabling the extension would clear the ban list). The ban is so that there would be only one error message per session per misbehaving player. I want logs for bug reports but in this case there's no need for more than one really. There's no need to spam the logs.

I'm still doing some tweaking.

**Comment by webmastak** [comment]
Waiting for fix )

**Comment by JasonLG1979** [comment]
> Waiting for fix )

Calm down. I'm still testing it with various players.

**Comment by JasonLG1979** [comment]
@webmastak there, https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/commit/691888e030ca334ed42608a5ee06e1045525088c makes sure players are MPRIS spec compliant and makes sure canControl is true otherwise the player is ignored.

**Comment by webmastak** [comment]
Yes, this is definitely necessary, thanks for the correction. )
