### ISSUE TITLE
Extra / non-standard padding around icon

### ISSUE THREAD

**Issue by hackel** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#29]
**Describe the bug**

I noticed that the icon looks a ever so slightly out of place next to my other indicators.  After taking screenshots to measure, it appears to have a 52px width vs 46px for the others.  I don't know if something is adding 3px of extra padding or if it's up to each extension and purely a coincidence that the others appear to be similar.   (Coming from Ubuntu AppIndicators?)  I would just love to see everything blend together seamlessly.

![image](https://user-images.githubusercontent.com/583677/74405306-67602500-4df2-11ea-9518-390616bc75cd.png)

**Comment by JasonLG1979** [comment]
The padding is the result of the ```'system-status-icon'``` style class being used. What the padding actually is is defined by the theme. That is the "standard" way to style indicators, if there was such a thing among GNOME Shell extensions (there isn't). At least that's what 99% of indicators use that I seen.

If by Ubuntu AppIndicators you mean https://github.com/ubuntu/gnome-shell-extension-appindicator then you need to talk to them. Looking at their code it seems that they hard code the equivalent padding for what ever reason? If you want the padding to match they are the outlier

**Comment by JasonLG1979** [comment]
For reference here is the [drive menu extension](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/blob/master/extensions/drive-menu/extension.js#L124) If anything represents a standard for indicators I think this would it.
