### ISSUE TITLE
Gnome 3.34.2 on ubuntu 19.10 can't display the indicator button of the latest update

### ISSUE THREAD

**Issue by i30817** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#32]
**Describe the bug**

Gnome 3.34.2 on ubuntu 19.10 can't display the indicator button of the latest update on 27/3/2020

There exists 'a' indicator in the date submenu of gnome shell that i think it's supposed to be the default one.

**Steps To Reproduce:**

1. run any player

**Logs**

journalctl says this:
```
mar 27 20:07:32 AIVAS gnome-shell[6647]: Received property Shuffle with type d does not match expected type b in the expected interface
mar 27 20:07:32 AIVAS gnome-shell[6647]: Received property Shuffle with type d does not match expected type b in the expected interface
mar 27 20:07:32 AIVAS gnome-shell[6647]: JS ERROR: Error: 3 is not a valid value for enumeration StAlign
                                         _init@/home/i30817/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:
                                         Player@/home/i30817/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js
                                         _init/<@/home/i30817/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.j
                                         _addPlayer/</<@/home/i30817/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/db
                                         onProxyReady@/home/i30817/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus
                                         makeProxy/<@/home/i30817/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus.
```

ALT+F2 followed by `lg` says 'mprisindicatorbutton@JasonLG1979.github.io has not emitted any errors' on the extension though.

**System Details (please complete the following information):**

 - **Extension version:** 
 - **Installed from:** GitHub
 - **GNOME/Shell version:** 3.34.2
 - **Distro/Release:** Ubuntu 19.10
 - **List of other installed and enabled Extensions*** Activities Configurator, Applications Menu, Desktop Icons, KStatusNotifierItem/AppIndicator Support, OpenWeather, Places Status Indicator, Radeon DPM Control (github version), Removable Drive Menu, gistnotes

**Comment by JasonLG1979** [comment]
This extension is only compatible with the latest version of GNOME.
