### ISSUE TITLE
After update to latest version extension doesn't work on Gnome 3.34

### ISSUE THREAD

**Issue by luetage** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#33]
**Describe the bug**

Mpris indicator icon doesn't show in panel

**Steps To Reproduce:**

Update to latest version or install fresh on Gnome 3.34

**Logs**

```
JS ERROR: Error: 3 is not a valid value for enumeration StAlign
_init@/home/castorp/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:819:28
Player@/home/castorp/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:997:28
_init/<@/home/castorp/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:1594:39
_addPlayer/</<@/home/castorp/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus.js:446:21
onProxyReady@/home/castorp/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus.js:268:17
makeProxy/<@/home/castorp/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/dbus.js:171:21
```

**System Details (please complete the following information):**

Fedora 31

**Additional Notes:**

After reading this github I'm confused, title states extension works for 3.34+, README states 3.36+. I'm assuming this just doesn't work on 3.34 anymore?

**Comment by JasonLG1979** [comment]
> title states extension works for 3.34+

Yep, sorry forgot to update that. This extension only ever tries to be compatible with the latest stable version of GNOME.
