### ISSUE TITLE
Many features not working in 20.04 Ubuntu

### ISSUE THREAD

**Issue by harsh-weather** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#34]
Hey, so I installed it on Ubuntu 20.04, and apart from the pause, forward, backward buttons, nothing else is visible on the drop down menu. Not even the album art, playlist etc. I am using it with Spotify.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide

**Comment by JasonLG1979** [comment]
The issue with album art in Spotify was fixed/worked around with https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/commit/de48a04a1a4c3b96379dfe074f7dce667e33f09a

A version with that fix was pushed to the extension site and is awaiting approval.

See https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/m-p/4929877 for the original bug report.
