### ISSUE TITLE
Mpris indicator didn'T recognise ANoise

### ISSUE THREAD

**Issue by kerozoli** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#37]
Mpris indicator didn't recognize ANoise
https://anoise.tuxfamily.org/

**Steps To Reproduce:**

Install and start ANoise

**Expected behavior**

Anoise could be controlled via mpris indicator

**System Details (please complete the following information):**

 - Installed from:GNOME Extensions Website
 - GNOME/Shell version:3,36
 - Distro/Release: Ubuntu 20.04

**Additional Notes:**

I don't know if this is an issue or a feature request, Thanks for checking

**Comment by JasonLG1979** [comment]
anoise's mpris interface is missing all properties. It's broken.
