### ISSUE TITLE
Scrolling on the icon to change the volumen

### ISSUE THREAD

**Issue by K3rcus** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#38]
I found more intuitive to use the mouse wheel to volume up and down and the mouse forward and back buttons to go next and previous song, usually when someone click forward or back want to go just one song at time, so one button seems better option, and using the wheel fits better with changing the volume.

I modified a little the "widgets.js" file to match this behaviour, but it would be nice to have it for everyone and as default behaviour.

**Comment by JasonLG1979** [comment]
A great many players do not have properly functioning volume controls. Combine that with the fact that not all mice have forward and back buttons and it makes more sense to map Functionality that's more likely to work with buttons that are more likely to be present.
