### ISSUE TITLE
Enhancement: Monochrome Icons

### ISSUE THREAD

**Issue by omeryagmurlu** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#4]
Currently, the Spotify icon is the only outsider in my top bar by being green. Having a toggle to enable monochrome icons would fix this problem.

I've read your stance on user configurable options [here](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/478), but in this case there isn't a sane default I'm afraid.

**Comment by JasonLG1979** [comment]
Symbolic(Monochrome) icons are preferred by default and full color icons are only used if a symbolic icon is not available. Spotify does not ship a symbolic icon with their desktop client, that is why you see a full color icon for Spotify. If you would like a symbolic Spotify icon in the panel you can file a bug with Spotify and tell them to ship a symbolic icon with their desktop client. In the meantime you could also make a symbolic icon of your own and name it sopitify-client-symbolic and put it in ~/.local/share/icons/

**Comment by JasonLG1979** [comment]
Here is a link to a Spotify press kit containing Spotify icons:
https://storage.googleapis.com/pr-newsroom-wp/1/2018/11/logo-and-brand-assets_20180427211714__bb7c4a59.zip

Download and unzip it and open the Spotify_Icon_RGB_Black.eps file in inkscape. Resize it and the doc size to 16x16px, set the fill color to bebebeff and save it as a normal svg as I said above. That's what I do.

**Comment by omeryagmurlu** [comment]
Thank you, using the given directory did the job. Thanks

**Comment by JasonLG1979** [comment]
Another note about Spotify. Since Spotify's volume property is broken and always returns 0 and setting it does nothing, Spotify will not have volume controls in extension. There's no point in showing volume controls that don't do anything.

**Comment by JasonLG1979** [comment]
I have an open PR to replace the png icons in the Spotify flatpak with svg's (svg's scale much better than png's and it means only one icon file per icon as opposed to a seperate file for each size) which includes a symbolic icon. So if you're a Spotify flatpak user soon you won't need to carry around your own symbolic icon. It should just work as expected in both the app menu and this extension.
