### ISSUE TITLE
Exclude Chrome player

### ISSUE THREAD

**Issue by webmastak** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#42]
When watching a video on youtube, a player appears, but after closing the tab, he does not disappear.
To hide the player you have to close Chrome.
![001](https://i.imgur.com/3yga8mW.png)

I can’t figure out where you can insert this piece of code to make it work?
```
let name_regex = /^org\.mpris\.MediaPlayer2\.(?!chrome)/; // exclude chrome
if (name_regex.test(player_name)) {
....
}
```
I don't need a Chome player.
Chrome already has a built-in.
![https://i.imgur.com/xL31Oco.png](https://i.imgur.com/xL31Oco.png)

**Comment by JasonLG1979** [comment]
This is a Chrome bug. They do not take down their interface after it's not needed anymore. It also has the nasty effect of stealing and never releasing the mediakeys. Their MPRIS implementation is shit.

**Comment by webmastak** [comment]
But still where you can insert this piece of code to make it work?
```
let name_regex = /^org\.mpris\.MediaPlayer2\.(?!chrome)/; // exclude chrome
if (name_regex.test(player_name)) {
....
}
```

**Comment by JasonLG1979** [comment]
You can disable mpris in chrome.
