### ISSUE TITLE
Possible to disable all artwork?

### ISSUE THREAD

**Issue by Scotty-Trees** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#45]
I know this kind of seems like an odd request, but on Pop!_OS 20.04, using some .deb and some flatpak apps, most do not display the album artwork. I'm actually starting to like just seeing the applications icon in the drop down menu of this extension instead of the artwork. It's simple, it's clean, and it's consistent, and all my application icons load just fine, nothing to fuss about. So I was wondering if it's possible to add like an *exclude artwork parameter or something? I notice the extension doesn't have any settings so it comes as is, so if it's possible then, would you be able to tell me if this is at all possible to do, aka hide/don't show artwork? Is there maybe a .json file or something where I could add or remove a line to achieve this? Don't know if this is at all possible, but I figured it couldn't hurt to ask since none of my apps want to play nice lol. Btw, here's a screenshot below to show most apps doesn't show artwork, so if I could disable artwork or prevent it from showing to only show just the application icon, that would be awesome! Thanks for taking the time to read this comment. 

![Screenshot from 2020-10-09 03-12-33](https://user-images.githubusercontent.com/45135187/95560035-47631e80-09de-11eb-81a7-a40dfe3f9540.png)

**Comment by JasonLG1979** [comment]
Nope sorry no config settings. You could add ```this.hide();``` after [this line](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/blob/master/mprisindicatorbutton%40JasonLG1979.github.io/widgets.js#L173)

So it looks like this:

```js

    _init() {
        super._init({
            style_class: 'popup-menu-icon',
            accessible_role: Atk.Role.ICON
        });
        this._useFallback = true;
        this._fingerPrint = '';
        this._coverArtIOHandler = CoverArtIOHandler.singleton;
        this._coverCallback = this._setCoverGicon.bind(this);
        this._fallback_gicon = Gio.ThemedIcon.new('audio-x-generic-symbolic');
        this.gicon = this._fallback_gicon;
        this._signals = [];
        this.pushSignal(this, 'destroy', this._onDestroy.bind(this));
        this.hide();
    }

```

That might do it?

**Comment by JasonLG1979** [comment]
You need to talk to the pop os people and tell them to fix their bug.

**Comment by Scotty-Trees** [comment]
Thanks for the reply! I tried the method above. It removes any hint of artwork/album art. But it also removes the application icon as well, which I was hoping to keep, if that's possible to show? Here's how it currently looks with your fix mentioned above for reference below. If you've got other things to take care of I understand man, I know this is a super small niche thing I'm asking for. 

![Screenshot from 2020-10-09 21-37-38](https://user-images.githubusercontent.com/45135187/95643913-20592b00-0a78-11eb-9642-7113528c3b2a.png)
