### ISSUE TITLE
Gnome 3.38 Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#46]
Gnome 3.38 has been released recently and Ubuntu 20.10 will have it and Pop!_OS should follow withe an update shortly after that too, and I would love to see this extension gain support for the latest version at some point in the future, I've grown very fond of it, thank you!

**Comment by JasonLG1979** [comment]
I tested it in a VM against Ubuntu 20.10 and Fedora 33 the other day. 1st time in a while a new GNOME version didn't break anything. I'll bump the version number before Ubuntu 20.10 is released.

**Comment by Scotty-Trees** [comment]
Ha, yeah always fingers crossed that some extensions don't break! But there's always at least one or two, but I've checked a handful and the ones I use, most of them are up to date, but I know it's not always easy to update it constantly after every release. Thanks for being very responsive and looking forward to update Gnome support. I'm on Pop!_OS so I believe we'll hit 3.38 sometime in the begging of November, so no rush man, enjoy the rest of your week :)

**Comment by JasonLG1979** [comment]
> Pop!_OS so I believe we'll hit 3.38 sometime in the begging of November

The current version of Pop!_OS is based off Ubuntu 20.04 right? I'm not 100% sure how Pop!_OS tracks Ubuntu but I'm thinking if you don't upgrade to the new version that tracks Ubuntu 20.10 you'll never see GNOME 3.38 as Ubuntu 20.04 will never be updated 3.38

> no rush man, enjoy the rest of your week :)

I will update and upload it to the extension site in a couple days so it should be available on the day Ubuntu 20.10 comes out. I'll be upgrading to 20.10 on my main machine then or shortly after and if any bugs show up I'll see what I can do to fix them and then I'll upload a bugfix release if needed.

**Comment by Scotty-Trees** [comment]
> The current version of Pop!_OS is based off Ubuntu 20.04 right?

Pop!_OS is a bit of a misnomer I feel, it does follow very closely to the latest Ubuntu, but it does so in a rolling release kind of way. Kind of how like KDE Neon has a base of Ubuntu, but updates Plasma elements quicker than Ubuntu, Pop! is kind of the same way, keeping the base of Ubuntu, but upgrading as much as possible to be current with the latest release of Ubuntu. No need to do a full wipe and install like in Elementary OS after each update, just run the update installer when a new version is out. It's rather simple and has been quite effective. 

> I'll be upgrading to 20.10 on my main machine

Hope your update goes smoothly. I tend to wait it out for a week or two, just to see what issues others have, since Gnome loves to "tinker" just a bit too much sometimes. But since they already have a point release out (3.38.1), that usually fixes most of the common bugs people have initially. I think if you don't hear from me in November things should be good to go ;)

**Comment by JasonLG1979** [comment]
I don't upgrade in place EVER. I always do a fresh install.

I've got my kids' computer that runs Mint (they picked Mint after I showed them a few distros) as a backup machine and I keep pretty good file backups so if anything goes wrong I can save myself. If all else fails I can just go back to 20.04. No worries.

**Comment by Scotty-Trees** [comment]
> I don't upgrade in place EVER.

It's just my own personal laptop which I backup each week, so I don't mind living a little dangerously when updating, but Pop! does a great job to minimize any risk and issue as best they can. A fresh install, that's like a days work to get everything back up and running just the way I need it, so hopefully I don't have to do that again this year ;)

**Comment by JasonLG1979** [comment]
> that's like a days work to get everything back up and running just the way I need it, so hopefully I don't have to do that again this year ;)

I enjoy tinkering. I do very little actual work on my computer(s) they're basically my toys,lol!!!

**Comment by Scotty-Trees** [comment]
> I do very little actual work

My doppelganger, ha ha jk. I do end up doing a clean wipe maybe once a year, so it's never out of the realm of things. I had to clean wipe Gnome 3.34 cuz so much was just broke. But I won't wipe unless I have to; I will admit it does feel nice having a clean, fresh install :P

**Comment by JasonLG1979** [comment]
My day job has absolutely nothing to do with computers ATM. Closest I come to a computer is reading the paperwork for the next truck I have to load,lol!!! Touching a computer at work is above my paygrade,lol!!!

**Comment by Scotty-Trees** [comment]
We all gotta do what we can to make ends meet and pay the bills. I sure wish my photography payed well enough, but don't worry man, be patient long enough and something could always come your way job wise that could better align to your interests. Until that dream is a reality for us though, pain and suffering is the joys of life :D

**Comment by JasonLG1979** [comment]
> something could always come your way job wise that could better align to your interests

My interests generally means being able to feed my family. There's no shame in my game. My background is laborer, manufacturing and warehousing. Basically I'm a grunt.. I like my current job. It could pay a little better (couldn't they all,lol!!!) but my boss is awesome and I like the guys I work with and I've been doing this type of work for like 20 years so I can do it in my sleep and there's plenty of overtime.

I don't know if I'd want to turn my hobby into a job? Might make it no fun anymore?

**Comment by Scotty-Trees** [comment]
I've done warehousing before for a year or two, but it never felt like I was valued much, if at all. I got outta there the second my life got turned upside down; a bunch of stuff out of my control that I ended up having to handle as best I could. If it's what you like and enjoy, there's definitely no harm if you're satisfied. But truth be told, I don't see you as a grunt man, I see you as a passionate individual doing something that's interesting and clearly beneficial to others. You got plenty of value and worth and I know you don't need to hear me say that, but I'm still gonna say it nonetheless! No need to let your job define you man, but also I get it we all tend to do that to some degree don't we? I can tell when put your mind to something you'll get it done no matter what, you'll try your best to figure it out. Hmm, you know what....come to think of it that sounds just like a grunt actually, ha kidding!

**Comment by JasonLG1979** [comment]
Thanks. What I mean is my job is to be a grunt, as in it's mostly physical labor. It's for sure not an intellectual pursuit,lol!!! Tinkering with computers is my intellectual stimulation. I'm always looking to learn something new. I think next I may teach myself Rust. It looks like an interesting language.

**Comment by Scotty-Trees** [comment]
>  I think next I may teach myself Rust

Some of the Solus devs I talk to like Rust a lot. JavaScript, not so much tho :P

**Comment by JasonLG1979** [comment]
> Some of the Solus devs I talk to like Rust a lot. JavaScript, not so much tho :P

Rust is attractive because it prevents you from making stupid mistakes from what I understand. Memory safety is a huge deal. JavaScript on the other hand in my experience is very loose and flexible. With all that freedom you can for sure shoot yourself in the foot. There's also the whole scripted vs compiled thing. A complied language is always going to be faster. You'd never write a device driver in JavaScript for example. Even if you could it would be many orders of magnitude slower then the same driver written in Rust. I think it's just a matter of making sure the language is suited for your use case.

**Comment by JasonLG1979** [comment]
GNOME Shell gets around a lot of the performance hit of using JavaScript in it's UI because even though for example this extension is written in js, 99% of the heavy lifting is actually done in the C code though language bindings.

**Comment by Scotty-Trees** [comment]
> I think it's just a matter of making sure the language is suited for your use case.

Pretty much this. Python and Go are other options to consider, but like you said it really just comes down to what you want to do with it. Hopefully you got some free time this year and can start to teach yourself a little bit of Rust, never hurts to know more than one way to code yourself out of a predicament or rather into one in some cases, lol.

**Comment by JasonLG1979** [comment]
I know a little Python. I started on Python. I'm one of the major contributors to [Pithos](https://github.com/pithos/pithos).

**Comment by JasonLG1979** [comment]
> rather into one in some cases

Premature optimization is the root of all evil,lol!!!

**Comment by Scotty-Trees** [comment]
Then you already know more Python than me! Now the sun's almost up and I have just enough time to try to capture a sunrise photo or two by the water. Pleasure chatting with you man! Hope you enjoy the rest of your week as well ;)

**Comment by JasonLG1979** [comment]
Done. I updated git master and uploaded to the GNOME Shell extension site. It should be approved pretty soon I'd think, the changes are very small.

**Comment by Scotty-Trees** [comment]
@JasonLG1979 Nice work man thank you! When Pop! get's updated in November I'm sure it'll be all smooth sailing :)
