### ISSUE TITLE
Add an option to "always display the icon as a note symbol"

### ISSUE THREAD

**Issue by mystiquewolf** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#47]
**Is your feature request related to a problem? Please describe.**
currently icon changes to something like a disk, it is hard to find if you have A LOT of icons.
**Describe the solution you'd like**
Add option or change default to always show the icon as a note symbol

**Comment by JasonLG1979** [comment]
The icon will be the icon of the current player or ```audio-x-generic-symbolic``` if no player icon is available. ```audio-x-generic-symbolic``` is usually some variation of a music note or notes in most icon themes. If you're unhappy with appearance of ```audio-x-generic-symbolic``` in your icon theme of choice you need to file a bug report with them.
