### ISSUE TITLE
Icon indicator not showing after launching audacious

### ISSUE THREAD

**Issue by smujaddid** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#48]
**Describe the bug**

Icon indicator not showing after launching audacious until the this extension re-enabled or (alt+f2)(r).

**Steps To Reproduce:**

1. Launch audacious
2. The icon indicator not showing
3. Re-enable this mpris extension or (alt+f2)(r)

**Expected behavior**

Launching audacious should immediately show the icon indicator without having to re-enable the extension or restarting shell.

**Screenshots**

**Logs**
```log
JS ERROR: Exception in callback for signal: hide: Error: Impossible to remove untracked message
removeMessage@resource:///org/gnome/shell/ui/messageList.js:677:19
_addPlayer/<@resource:///org/gnome/shell/ui/mpris.js:273:18
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_updateState@resource:///org/gnome/shell/ui/mpris.js:231:22
_onPlayerProxyReady@resource:///org/gnome/shell/ui/mpris.js:181:14
_makeProxyWrapper/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:262:21
```
**System Details (please complete the following information):**

 - **Extension version:** 16
 - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36.4
 - **Distro/Release:** Ubuntu 20.04
 - **List of other installed and enabled Extensions***
   - Arc Menu version 4
   - Dash to Panel version 40
 - **Audacious version:** 3.10.1

**Additional Notes:**

**Comment by JasonLG1979** [comment]
That looks like a problem with audacious. None of those errors are from this extension. Those errors are being thrown by the default mpris controls.

Audacious 3.10.1 was released in December 2018. The current stable is 4.0.5. 4.0.5 is available at https://flathub.org/apps/details/org.atheme.audacious .

I could not duplicate your issue on Ubuntu 20.10 GNOME 3.38 and Audacious 4.0.5. I would suggest you update Audacious.

Also please note that although it should still work (at least for the time being) GNOME 3.36 is no longer supported by this extension.

**Comment by smujaddid** [comment]
Thank you! I'll try to update the audacious to current stable version first. It is working as intended for GNOME 3.36 except the icon indicator problem.

It is unfortunate that Ubuntu 20.04 will be sticking to 3.36 and I can't update my OS to non-LTS version because of my works. But, as long as it is working, I have no problem.

**Comment by JasonLG1979** [comment]
> It is unfortunate that Ubuntu 20.04 will be sticking to 3.36 and I can't update my OS to non-LTS version because of my works. But, as long as it is working, I have no problem.

It would not be a problem if the GNOME folks didn't break extensions with every release. 3.36 -> 3.38 is the 1st update since I started this extension that it didn't break. That's the reason I only support the latest GNOME Shell version, because I don't have the time or patience to keep track of and fix bugs and breakages for a bunch of different versions.
