### ISSUE TITLE
Add functionali exclude player

### ISSUE THREAD

**Issue by webmastak** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#50]
Please add functionali exclude player for developers!!!!!

Let it be in code like  `this._ignoredPlayers = ['olivia'];`  developers will take advantage of it, and ordinary users won't even know about it.

Extension mpris-indicator-button with the olivia player works disgustingly. If you do not enable MPRIS, then the mpris-indicator-button is not active but there is no control from the multimedia keys.

I tried to hack bus.js  through `this._ignoredPlayers = [];`  replace on  `this._ignoredPlayers = ['olivia'];` 
But I didn't succeed. 

Although judging by this code` if (busName.startsWith(MPRIS_PREFIX) && !this._ignoredPlayers.includes(this._stripInstanceNumber(busName))) { `
 Where `!this._ignoredPlayers.includes(this._stripInstanceNumber(busName))` should work.

**Comment by JasonLG1979** [comment]
> Please add functionali exclude player for developers!!!!!

> Extension mpris-indicator-button with the olivia player works disgustingly. If you do not enable MPRIS, then the mpris-indicator-button is not active but there is no control from the multimedia keys.

No. Tell them to fix their bugs.

> I tried to hack bus.js through this._ignoredPlayers = []; replace on this._ignoredPlayers = ['olivia'];
But I didn't succeed.

> Although judging by this codeif (busName.startsWith(MPRIS_PREFIX) && !this._ignoredPlayers.includes(this._stripInstanceNumber(busName))) {
Where !this._ignoredPlayers.includes(this._stripInstanceNumber(busName)) should work.

`olivia` is the app's name not it's bus name. The bus name starts with `org.mpris.MediaPlayer2.` and generally contains the app's name and maybe an instance value. Try `org.mpris.MediaPlayer2.olivia`
