### ISSUE TITLE
[Feature Request] Auto-pause when new source is playing

### ISSUE THREAD

**Issue by Aurnytoraink** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#52]
**Is your feature request related to a problem? Please describe.**
When I you play a song and then play a second one, the first one isn't paused

**Describe the solution you'd like**
Pause the first one and make it work in the other sens

**Comment by JasonLG1979** [comment]
It's not the job of this extension to make sure only one player is playing at a time.
