### ISSUE TITLE
Do not show application icons

### ISSUE THREAD

**Issue by gmg137** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#53]
Hi, I am developing a music player using GTK, how do I set it up to show the application icon in the tray?

**Comment by JasonLG1979** [comment]
Follow the MPRIS spec, in particular the [DesktopEntry](https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:DesktopEntry) part.

**Comment by gmg137** [comment]
Thank you very much.
