### ISSUE TITLE
No volume bar (when using spotify)

### ISSUE THREAD

**Issue by lollilol** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#54]
**Description of the bug**

Im using the spotify flatpak v1.1.46.916.g416cacf1, and when im listening to music with it, the volume bar and other stuff like shuffle and repeat or the playlist thing does not appear when opening the extension panel.

**Steps To Reproduce:**

1. Make sure flatpak is installed
2. Issue the command `flatpak install com.spotify.Client`
3. Open spotify trough gnome search or issue `flatpak run com.spotify.Client`
4. Click on the extension

**Expected behavior**

The things should appear

**Screenshots**

![image](https://user-images.githubusercontent.com/38194372/109399043-9c2d1480-7940-11eb-8b4e-ae6f1d301937.png)

**Logs**

Search your logs for "mpris".
im not sure how to do that exactly

**System Details (please complete the following information):**

 - **Extension version:** i didnt find a version number but i used the latest today
 - **Installed from:** gnome.extensions.org
 - **GNOME/Shell version:** 3.38.4 on Wayland
 - **Distro/Release:** Fedora 33
 - **List of other installed and enabled Extensions**
 - [Audio output switcher](https://extensions.gnome.org/extension/751/audio-output-switcher/)
 - [Dash to dock](https://extensions.gnome.org/extension/307/dash-to-dock/)
 - [Gsconnect](https://extensions.gnome.org/extension/1319/gsconnect/)
 - [Netspeed](https://extensions.gnome.org/extension/104/netspeed/)
 - [Topicons Plus](https://extensions.gnome.org/extension/1031/topicons/)

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide
