### ISSUE TITLE
Flathub's Firefox 86 album art image not displayed

### ISSUE THREAD

**Issue by luizhfsilva** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#56]
**Describe the bug**

Opening either Youtube Music or Spotify Web Player on the latest version of Firefox (86.0) from Flathub, the extension won't display any cover art. Fixed by installing Firefox 86 directly from Debian unstable.

**Steps To Reproduce:**

1. Install and run Firefox from Flathub
2. Go to Youtube Music or Spotify web player and hit play
3. Click on extension icon in Gnome Shell
4. There's a music note icon where cover art should be

**Expected behavior**

Cover art displayed in steps above.

**Logs**

```
JS ERROR: Extension mprisindicatorbutton@JasonLG1979.github.io: Gio.IOErrorEnum: Error opening file /home/my-user/.mozilla/firefox/firefox-mpris/2_9.png: No such file or directory
getCover/<@/home/my-user/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:70:50
```

**System Details :**

 - **Extension version:** 16
 - **Installed from:** GNOME Extensions website
 - **GNOME/Shell version:** 3.38.3-3
 - **Distro/Release:** Debian 11 (testing)

**Additional Notes:**

I'm able to open the `file:///home/my-user/.mozilla/firefox/firefox-mpris/2_9.png` on Flatpak's Firefox's navigation bar, but not anywhere else. The folder does not exist under `~/.mozilla/firefox` when I open it via terminal.

I ended up uninstalling Firefox from Flathub, and instead installed it from Debian's unstable repository, [following more or less this stackexchange answer](https://unix.stackexchange.com/a/253866/105168). Now it works and provides the Artwork as expected. The folder with cover art can now be seen at `~/.mozilla/firefox/firefox-mpris/`.

**Comment by JasonLG1979** [comment]
Flatpaks generally store user data in  `~/.var/app/<app-id>`.

The Firefox flatpak is storing MPRIS cover art in `~/.var/app/org.mozilla.firefox/.mozilla/firefox/firefox-mpris/` which is correct but it is giving out the wrong location via it's MPRIS interface.

This is a Firefox bug. File a report with them.

**Comment by JasonLG1979** [comment]
As a quick and dirty fix in the meantime if you really want the flatpak version you can symlink `~/.var/app/org.mozilla.firefox/.mozilla` to `~/.mozilla/firefox`.

1. Uninstall the apt version.

`sudo apt purge firefox -y`

2. Delete the old .mozilla folder. ( This will delete the apt installed Firefox user data. )

`rm -rf .mozilla`

3. Install the flatpak version.

`flatpak install flathub org.mozilla.firefox`

4. Create a symlink'd .mozilla folder that points to the flatpak's .mozilla folder.

`ln -s .var/app/org.mozilla.firefox/.mozilla .mozilla`

**Comment by luizhfsilva** [comment]
> This is a Firefox bug. File a report with them.
Done: https://bugzilla.mozilla.org/show_bug.cgi?id=1696903 . 

> Uninstall the apt version.
to be safe I did: `sudo apt purge firefox firefox-esr`

> Create a symlink'd .mozilla folder that points to the flatpak's .mozilla folder.
This worked and now the Extension shows the artwork. Thanks for your help!
