### ISSUE TITLE
Option to incorporate into the menu on the right.

### ISSUE THREAD

**Issue by stuaxo** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#59]
I realise this is gnome-shell-extension-mpris-indicator-*button* but this is the only mpris controller that seems to work any more.

It would be good if there was a setting to incorporate this into the user menu on the right (with volume, wifi etc) instead of having its own button.

I've got quite a too much stuff on my toolbar, and it would save me one little space.

**Comment by JasonLG1979** [comment]
I'm sorry but that's not going to happen. As you noticed it's *button*, and it's *button* for a reason. The aggregate menu (the one you're talking about) is not a fun place to be for fairly visually/structurally complex extensions. You just end up fighting it's structure and writing really hacky code to make sure your extension looks the way it's supposed to but also matches the rest of the look and feel of the rest of the aggregate menu without also messing up the rest of the aggregate menu. The aggregate menu is written or designed to have anything but simple one level drop down menus.

**Comment by stuaxo** [comment]
Thanks for the detailed explanation .. it feels like a lot of gnome shell could be better designed for extension (witnessing so many things breaking on update).

Between app indicators, legacy icons and various bits I probably just have too many things in my top bar and should work out some other solution - on my laptop everything doesn't fit, and gnome shell doesn't provide a way to easily scroll to the rest of the icons.

![image](https://user-images.githubusercontent.com/179677/122313424-198b8d80-cf0e-11eb-8417-efe26f37e9ba.png)

**Comment by JasonLG1979** [comment]
> Thanks for the detailed explanation .. it feels like a lot of gnome shell could be better designed for extension (witnessing so many things breaking on update).

No problem. There is an API in the works from what I hear.

> Between app indicators, legacy icons and various bits I probably just have too many things in my top bar and should work out some other solution - on my laptop everything doesn't fit, and gnome shell doesn't provide a way to easily scroll to the rest of the icons.

You do have a lot of stuff going on there,lol!!! I don't fool with legacy icons. (or really any other extension beyond the ones I wrote) They go against the design principle of GNOME Shell. The idea being that app icons shouldn't live in the panel just to provide what 99.99% of the time can be provided by a notification.

**Comment by stuaxo** [comment]
Ha, well this got me to rationalise my extensions.. the app indicators are harder as there are a couple of apps I do want to see.

At least it all fits on my laptop screen now.

![image](https://user-images.githubusercontent.com/179677/122476589-6333b100-cfbe-11eb-9312-55f1ad728068.png)
