### ISSUE TITLE
JS Error in _getIcon for Strawberry player (tested on Gnome 40)

### ISSUE THREAD

**Issue by Mershl** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#60]
**Describe the bug**

JS error is visible in log when starting strawberry player (https://github.com/strawberrymusicplayer/strawberry). Spotify does not show this issue.

Gtk.IconTheme.get_default() can return NULL. _getIcon is not handling that case.

**Steps To Reproduce:**

1. Have latest gnome-shell-extension-mpris-indicator-button installed
2. Start strawberry player (tested with 0.9.3)
3. Check logs e.g. `journalctl -b -p4`

**Logs**

`JS ERROR: TypeError: Gtk.IconTheme.get_default() is null`

**System Details:**

 - **Installed from:** git
 - **GNOME/Shell version:** 40
 - **Distro/Release:** Fedora 34
 - **Used Icon Theme:** Yaru (https://github.com/ubuntu/yaru)

**Comment by Mershl** [comment]
A quick hack fixes the issue and let's the extension work as before.

```diff
<         return this.app_id && (Gtk.IconTheme.get_default() ? Gtk.IconTheme.get_default().has_icon(iconName) : false) ? Gio.ThemedIcon.new(iconName) : null;
---
>         return this.app_id && Gtk.IconTheme.get_default().has_icon(iconName) ? Gio.ThemedIcon.new(iconName) : null;
```

Interesting enough. A nice icon is shown:

![image](https://user-images.githubusercontent.com/520251/125981788-645a469c-58f3-450f-9e32-159a98ac108d.png)

**Comment by JasonLG1979** [comment]
@Mershl if that fixes the issue, put in a Pull Request and I'll give it a go, and if all goes well I'll merge it.
