### ISSUE TITLE
Possible to remove/hide Playlist option?

### ISSUE THREAD

**Issue by Scotty-Trees** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#63]
Greetings!

Been using your lovely extension for over a year or more, through a few releases and it comes in handy everyday, so thank you for making it available still. I'm currently on EndeavourOS Gnome 41.1, using the latest version of your extension v19. Some music apps I have like Tauon don't show any option for playlists to be displayed in your extension. It just shows the play controls and personally I like that approach and look. When I use Rhythmbox, I get the play controls as well as a little extra drop down to show the playlists I have. Even if I delete the playlists (i don't use playlists btw), it'll still show since for some reason Rhythmbox thinks the Play Queue is also a playlist, which I guess is technically true, but it's built into the app so it's not a playlist I can simply delete.

I'm wondering if there's a setting in a .json file or config file in the extension that I could remove or mark out that would hide the drop down menu for the playlist? Please let me know if this is possible or not. Just something I've been curious about for a while, but just thought I'd post for any comment or feedback. Please let me know what you think and thanks again for making a great extension!

Below is the Playlists drop down menu I'm referring to that I'd like to remove or hide if possible:

![Screenshot from 2021-12-02 18-38-36](https://user-images.githubusercontent.com/45135187/144520553-aca0b6ce-e2b4-4488-8f6e-289b04602aa8.png)

**Comment by JasonLG1979** [comment]
No there's no config. What is shown is up to what the player is exposing as far as MPRIS interfaces and functionality. If there shouldn't be a playlist exposed via MPRIS in your opinion in that situation that would be something that you should take up with the Rhythmbox devs.

**Comment by Scotty-Trees** [comment]
Ah okay no worries, thanks for clearing that up, I appreciate your answer! :)
