### ISSUE TITLE
[Help] - Tray Icon

### ISSUE THREAD

**Issue by Dvlnst** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#65]
Hi,

This is not a bug or feature requests. I'm reaching you out to ask if you could help me with the tray icon. I'm using a custom theme (Numix) which have lot of symbolic icons (Spotify included) and it's working on all apps but not in this extensions. How is the icon loaded from this extension?

Currently using Gnome 42.

Kind regards.

**Comment by JasonLG1979** [comment]
I did a quick [search](https://github.com/search?q=org%3Anumixproject+spotify-client-symbolic) of the Numix repos and can't find an icon called `spotify-client-symbolic` and the Spotify .deb and snap do not ship their own symbolic icon. I actually created a symbolic icon for the flatpak so you can either use the flatpak, ask the numix folks to include a symbolic icon or ask Spotify to include it.

**Comment by JasonLG1979** [comment]
To answer your question directly. It looks for icons by name just like every other app.

**Comment by Dvlnst** [comment]
I manually placed those icons with that name in my installed theme (copying and renaming the current ones), but the extension doesn't load them. I also updated the icons cache and restarted gnome shell, but it's not working neither. That's why I was asking if you would know how to solve it.

**Comment by JasonLG1979** [comment]
Custom icons should not be placed in the system-wide icon theme as they can be overwritten on update.

If you want to add your own `spotify-client-symbolic` icon for a native package you should put it in `~/.local/share/icons/hicolor/symbolic/apps/` (that folder may not exist and you may have to create it.)

For the snaps I'm not sure how the namespacing works so you'll need to figure that out for yourself. All of this is really out of scope of the extension and are upstream issues so you're on your own.

**Comment by JasonLG1979** [comment]
File a bug upstream.
