### ISSUE TITLE
It looks like mpris-indicator-button toggles the LoopStatus on startup of sonixd

### ISSUE THREAD

**Issue by kowalcj0** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#66]
**Describe the bug**
Hi,

Thank you for this extension, it's really handy!
Recently I started using [sonixd](https://github.com/jeffvli/sonixd) player which when starts seems to have the `Repeat`  button toggled by `mpris-indicator-button` extension.
This issue seems to be related with the older #49 .
Similar problem was also reported for sonixd -> see https://github.com/jeffvli/sonixd/issues/277
To depict this issue I've added some basic logging to `dbus.js` (see screencast 1) which is visible in the output of `journalctl -f`.

**Steps To Reproduce:**

### Scenario 1: start sonixd multiple times with `mpris-indicator-button` extension enabled
1. Go to 'Extension' and ensure that `mpris-indicator-button` extension is enabled
2. start `dbus-monitor | grep -B1 -A1 -C2 LoopStatus` and `journalctl -f`
3. Start sonixd multiple times
4. Check logs and status of the Repeat button in sonixd

### Scenario 2: start sonixd multiple times with `mpris-indicator-button` extension disable
1. Go to 'Extension' and ensure that `mpris-indicator-button` extension is dusabled
2. start `dbus-monitor | grep -B1 -A1 -C2 LoopStatus` and `journalctl -f`
3. start sonixd multiple times
4. Check logs and status of the Repeat button in sonixd. It should be preserved between app restarts

### Scenario 3: start sonixd then toggle `mpris-indicator-button` extension multiple times
1. Go to 'Extension' and ensure that `mpris-indicator-button` extension is disabled
2. start `dbus-monitor | grep -B1 -A1 -C2 LoopStatus` and `journalctl -f`
3. Start sonixd
4. Turn the `mpris-indicator-button` extension on and off multiple times
5. Check logs and status of the Repeat button in sonixd

**Expected behavior**

The repeat/loop status in sonixd shouldn't change when `mpris-indicator-button` extension is enabled.

**Screencasts**

### Scenario 1

https://user-images.githubusercontent.com/910451/187550326-10fd04c2-e0eb-4c9e-9ea7-34c396e19190.mp4

### Scenario 2

https://user-images.githubusercontent.com/910451/187550357-fe7b1d9c-0f80-4832-8913-183962e223f1.mp4

### Scenario 3

https://user-images.githubusercontent.com/910451/187550396-a1115ff2-a237-4b07-91ba-aec5940027ad.mp4

**Logs**

dbus logs:
[turn_on_mpris_indicator_dbus.log](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/files/9456846/turn_on_mpris_indicator_dbus.log)

[start_sonixd_mpris_indicator_on_dbus.log](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/files/9456850/start_sonixd_mpris_indicator_on_dbus.log)

[start_sonixd_mpris_indicator_off_dbus.log](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/files/9456851/start_sonixd_mpris_indicator_off_dbus.log)

[start_sonixd_then_start_mpris_indicator_dbus.log](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/files/9456853/start_sonixd_then_start_mpris_indicator_dbus.log)

**System Details (please complete the following information):**

 - **Extension version:** 20
 - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 42.4
 - **Distro/Release:** Fedora 36
 - **List of other installed and enabled Extensions*** 
![Extensions](https://user-images.githubusercontent.com/910451/187549197-db356d98-32a6-4b62-b1dc-96bb69b01113.png)

**Additional Notes:**

N/A

Thanks

**Comment by JasonLG1979** [comment]
As noted in https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/49 poking the properties is the only way to see if they actually work. If sonixd's MPRIS interface were fully functional before it were exposed it would not be a problem. It's a bug on their side for exposing the interface prematurely.
