### ISSUE TITLE
Option to put Indicator in the center of the panel

### ISSUE THREAD

**Issue by roizcorp** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#7]
So I know, settings are big no no in the new paradigm but I think that once you will add the current song that will be relevant as of where I want to see the current song.

I personally would like to have it in the center (moved the clock aside) instead of "competing" with other extensions for real estate and alignment priority

Thoughts?

**Comment by JasonLG1979** [comment]
I'm going to have to pass on this one. Sorry.

**Comment by JasonLG1979** [comment]
As I've said I want to avoid settings at all costs, preferring sane defaults or features that automatically reveal them self when they're applicable and actually work like the volume controls.

**Comment by roizcorp** [comment]
OK, I'm not sure if that's a big no no as well so I will suggest the alternative either way (do not want to nag): a button that changes the position of the indicator (in the player)

long shot, but here it is. do as you please.

**Comment by JasonLG1979** [comment]
> a button that changes the position of the indicator (in the player)

You would still need to have a way to remember the preference. The compromise would be to have options but no options UI so that power users could change the settings but officially the options are not supported. But that's a bit of an Anti-pattern.

**Comment by JasonLG1979** [comment]
I really just don't want to have to compile or build anything to install the extension. Right now it's just a matter of copy and paste.

**Comment by roizcorp** [comment]
> > a button that changes the position of the indicator (in the player)
> 
> You would still need to have a way to remember the preference. The compromise would be to have options but no options UI so that power users could change the settings but officially the options are not supported. But that's a bit of an Anti-pattern.

That's actually pretty cool, but I totally understand...as you wish :)
